if not(GetLocale() == "ptBR") then
    return;
end

local L = WeakAuras.L

-- Options translation
L["<"] = "<"
L["<="] = "<="
L["="] = "="
L[">"] = ">"
L[">="] = ">="
L["!="] = "!="
L["10 Man Raid"] = "Raide de 10 jogadores"
L["25 Man Raid"] = "Raide de 25 jogadores"
L["5 Man Dungeon"] = "Masmorra de 5 jogadores"
L["Absorb"] = "Absorver"
L["Absorbed"] = "Absorvido"
L["Action Usable"] = "Ação Usável"
L["Affected"] = "Afetado"
L["Air"] = "Ar"
L["Alive"] = "Vivo"
L["All Triggers"] = "Todos os Gatilhos"
L["Alternate Power"] = "Alternar Poder" -- Needs review
L["Ambience"] = "Ambiente"
L["Amount"] = "Quantidade"
L["Any Triggers"] = "Qualquer Gatilhos" -- Needs review
L["Arena"] = "Arena" -- Needs review
L["Ascending"] = "Ascendente" -- Needs review
L["At Least One Enemy"] = "Pelo Menos Um Inimigo"
-- L["Attackable"] = ""
L["Aura"] = "Aura" -- Needs review
L["Aura:"] = "Aura:" -- Needs review
L["Aura Applied"] = "Aura Aplicada"
-- L["Aura Applied Dose"] = ""
L["Aura Broken"] = "Aura violada" -- Needs review
L["Aura Broken Spell"] = "Feitiço violar de aura" -- Needs review
L["Aura Name"] = "Nome da Aura" -- Needs review
L["Aura Refresh"] = "Aura Restaurada" -- Needs review
L["Aura Removed"] = "Aura Removida" -- Needs review
-- L["Aura Removed Dose"] = ""
L["Auras:"] = "Auras:" -- Needs review
-- L["Aura Stack"] = ""
L["Aura Type"] = "Tipo de Aura" -- Needs review
L["Automatic"] = "Automático"
-- L["Back and Forth"] = ""
L["Battleground"] = "Campo de Batalha" -- Needs review
L["Battle.net Whisper"] = "Battle.net Sussuro" -- Needs review
L["BG>Raid>Party>Say"] = "CB>Raid>Grupo>Fala" -- Needs review
L["BG-System Alliance"] = "CB-Sistema da Aliança"
L["BG-System Horde"] = "CB-Sistema da Horda"
L["BG-System Neutral"] = "CB-Sistema Neutro" -- Needs review
L["Blizzard Combat Text"] = "Texto de Combate da Blizzard" -- Needs review
L["Block"] = "Bloquear" -- Needs review
L["Blocked"] = "Bloqueado" -- Needs review
L["Blood Rune #1"] = "Runa de Sangue#1" -- Needs review
L["Blood Rune #2"] = "Runa de Sangue#2" -- Needs review
-- L["Blood runes"] = ""
L["Boss Emote"] = "Emote do Chefe" -- Needs review
L["Bottom"] = "Embaixo" -- Needs review
L["Bottom Left"] = "Embaixo à esquerda" -- Needs review
L["Bottom Right"] = "Embaixo à direita" -- Needs review
L["Bottom to Top"] = "De baixo para cima" -- Needs review
L["Bounce"] = "Salto" -- Needs review
L["Bounce with Decay"] = "Salto com declínio" -- Needs review
-- L["Buff"] = ""
L["By |cFF69CCF0Mirrored|r of Dragonmaw(US) Horde"] = "Por |cFF69CCF0Mirrored|r of Dragonmaw(US) Horde" -- Needs review
L["Cast"] = "Lançar" -- Needs review
L["Cast Failed"] = "Lançamento falho" -- Needs review
L["Cast Start"] = "Começar lançamento" -- Needs review
L["Cast Success"] = "Sucesso no lançamento" -- Needs review
L["Cast Type"] = "Tipo de lançamento" -- Needs review
L["Center"] = "Centro" -- Needs review
L["Centered Horizontal"] = "Centralizado Horizontalmente" -- Needs review
L["Centered Vertical"] = "Centralizado Verticalmente" -- Needs review
L["Channel"] = "Canal" -- Needs review
L["Channel (Spell)"] = "Canal (Feitiço)" -- Needs review
L["Character Type"] = "Tipo de personagem" -- Needs review
L["Chat Frame"] = "Quadro do bate-papo" -- Needs review
L["Chat Message"] = "Mensagem de bate-papo" -- Needs review
-- L["Children:"] = ""
L["Circle"] = "Círculo" -- Needs review
L["Circular"] = "Circular" -- Needs review
L["Class"] = "Classe" -- Needs review
L["Click to close configuration"] = "Clique para fechar a configuração" -- Needs review
L["Click to open configuration"] = "Clique para abrir a configuração" -- Needs review
L["Combat Log"] = "Registro de combate" -- Needs review
L["Combo Points"] = "Pontos de combo" -- Needs review
L["Conditions"] = "Condições" -- Needs review
L["Contains"] = "Contém" -- Needs review
L["Cooldown Progress (Item)"] = "Curso do tempo de recarga (Item)" -- Needs review
L["Cooldown Progress (Spell)"] = "Curso do tempo de recarga (Feitiço)" -- Needs review
L["Cooldown Ready (Item)"] = "Tempo de recarga finalizado (Item)" -- Needs review
L["Cooldown Ready (Spell)"] = "Tempo de recarga finalizado (Item)" -- Needs review
L["Create"] = "Criar" -- Needs review
L["Critical"] = "Crítico" -- Needs review
L["Crowd Controlled"] = "Sob efeito de C/C" -- Needs review
L["Crushing"] = "Esmagador" -- Needs review
L["Curse"] = "Maldição" -- Needs review
L["Custom"] = "Personalizado" -- Needs review
L["Custom Function"] = "Função personalizada" -- Needs review
L["Damage"] = "Dano" -- Needs review
L["Damager"] = "Causador de dano" -- Needs review
L["Damage Shield"] = "Escudo de Dano" -- Needs review
L["Damage Shield Missed"] = "Escudo de dano falho" -- Needs review
L["Damage Split"] = "Dano dividido" -- Needs review
L["Death Knight"] = "Cavaleiro da Morte" -- Needs review
L["Death Knight Rune"] = "Runa de Cavaleiro da Morte" -- Needs review
-- L["Death Rune"] = ""
-- L["Debuff"] = ""
-- L["Deflect"] = ""
-- L["Descending"] = ""
-- L["Destination Name"] = ""
-- L["Destination Unit"] = ""
-- L["Disease"] = ""
-- L["Dispel"] = ""
-- L["Dispel Failed"] = ""
-- L["Dodge"] = ""
-- L["Done"] = ""
-- L["Down"] = ""
-- L["Drain"] = ""
-- L["Drowning"] = ""
-- L["Druid"] = ""
-- L["Dungeon Difficulty"] = ""
-- L["Durability Damage"] = ""
-- L["Durability Damage All"] = ""
-- L["Earth"] = ""
-- L["Eclipse Direction"] = ""
-- L["Eclipse Power"] = ""
-- L["Eclipse Type"] = ""
-- L["Emote"] = ""
-- L["Energize"] = ""
-- L["Energy"] = ""
-- L["Enrage"] = ""
-- L["Environmental"] = ""
-- L["Environment Type"] = ""
-- L["Evade"] = ""
-- L["Event"] = ""
-- L["Event(s)"] = ""
-- L["Every Frame"] = ""
-- L["Extra Amount"] = ""
-- L["Extra Attacks"] = ""
-- L["Extra Spell Name"] = ""
-- L["Fade In"] = ""
-- L["Fade Out"] = ""
-- L["Falling"] = ""
-- L["Fatigue"] = ""
-- L["Fire"] = ""
-- L["First Tree"] = ""
-- L["Flash"] = ""
-- L["Flip"] = ""
-- L["Focus"] = ""
-- L["Form"] = ""
-- L["Friendly"] = ""
-- L["From"] = ""
-- L["Frost Rune #1"] = ""
-- L["Frost Rune #2"] = ""
-- L["Frost Runes"] = ""
-- L["Glancing"] = ""
-- L["Global Cooldown"] = ""
-- L["Glow"] = ""
-- L["Gradient"] = ""
-- L["Gradient Pulse"] = ""
-- L["Group"] = ""
-- L["Group %s"] = ""
-- L["Grow"] = ""
-- L["Guild"] = ""
-- L["Happiness"] = ""
-- L["HasPet"] = ""
-- L["Heal"] = ""
-- L["Healer"] = ""
-- L["Health"] = ""
-- L["Health (%)"] = ""
-- L["Heroic"] = ""
-- L["Hide"] = ""
-- L["Higher Than Tank"] = ""
-- L["Holy Power"] = ""
-- L["Hostile"] = ""
-- L["Hostility"] = ""
-- L["Humanoid"] = ""
-- L["Hunter"] = ""
-- L["Icon"] = ""
-- L["Ignore Rune CD"] = ""
-- L["Immune"] = ""
-- L["Include Bank"] = ""
-- L["Include Charges"] = ""
-- L["Include Death Runes"] = ""
-- L["In Combat"] = ""
-- L["Inherited"] = ""
-- L["Inside"] = ""
-- L["Instakill"] = ""
-- L["Instance Type"] = ""
-- L["Interrupt"] = ""
-- L["Interruptible"] = ""
-- L["In Vehicle"] = ""
-- L["Inverse"] = ""
-- L["Is Exactly"] = ""
-- L["Item"] = ""
-- L["Item Count"] = ""
-- L["Item Equipped"] = ""
L["Lava"] = "Lava" -- Needs review
L["Leech"] = "Sugar" -- Needs review
L["Left"] = "Esquerda" -- Needs review
L["Left to Right"] = "Da esquerda para direita" -- Needs review
-- L["Level"] = ""
L["Lower Than Tank"] = "Menor que o tanque" -- Needs review
L["Lunar"] = "Lunar" -- Needs review
L["Lunar Power"] = "Poder Lunar" -- Needs review
L["Mage"] = "Mago" -- Needs review
L["Magic"] = "Mágico" -- Needs review
L["Main Hand"] = "Mão principal" -- Needs review
L["Mana"] = "Mana" -- Needs review
L["Master"] = "Mestre" -- Needs review
-- L["Matches (Pattern)"] = ""
L["Message"] = "Mensagem" -- Needs review
L["Message type:"] = "Tipo de mensagem:" -- Needs review
L["Message Type"] = "Tipo de mensagem" -- Needs review
L["Miss"] = "Falha" -- Needs review
L["Missed"] = "Falho" -- Needs review
L["Missing"] = "Faltando" -- Needs review
L["Miss Type"] = "Tipo de falha" -- Needs review
-- L["Monochrome"] = ""
L["Monster Yell"] = "Grito do monstro" -- Needs review
L["Mounted"] = "Montado" -- Needs review
L["Multi-target"] = "Multi-alvo" -- Needs review
L["Music"] = "Música" -- Needs review
L["Name"] = "Nome" -- Needs review
L["Never"] = "Nunca" -- Needs review
L["Next"] = "Próximo" -- Needs review
-- L["No Children:"] = ""
L["No Instance"] = "Fora da instância" -- Needs review
L["None"] = "Nenhum" -- Needs review
-- L["Non-player Character"] = ""
L["Normal"] = "Normal" -- Needs review
-- L["Not On Threat Table"] = ""
L["Number"] = "Número" -- Needs review
L["Number Affected"] = "Número Afetado" -- Needs review
L["Off Hand"] = "Mão secundária" -- Needs review
L["Officer"] = "Oficial" -- Needs review
-- L["Opaque"] = ""
L["Orbit"] = "Órbita" -- Needs review
-- L["Outline"] = ""
L["Outside"] = "Exterior" -- Needs review
L["Overhealing"] = "Sobrecura" -- Needs review
L["Overkill"] = "Sobreassassinato" -- Needs review
L["Paladin"] = "Paladino" -- Needs review
L["Parry"] = "Aparar" -- Needs review
L["Party"] = "Grupo" -- Needs review
L["Party Kill"] = "Assassinato do grupo" -- Needs review
L["Paused"] = "Pausado" -- Needs review
L["Periodic Spell"] = "Feitiço periódico" -- Needs review
L["Pet"] = "Assistente" -- Needs review
L["Player"] = "Jogador" -- Needs review
L["Player Character"] = "Personagem do jogador" -- Needs review
L["Player Class"] = "Classe do jogador" -- Needs review
L["Player Dungeon Role"] = "Função do jogador na masmorra" -- Needs review
L["Player Level"] = "Nível do jogador" -- Needs review
L["Player Name"] = "Nome do jogador" -- Needs review
L["Player(s) Affected"] = "Jogado(res) afetados" -- Needs review
L["Player(s) Not Affected"] = "Jogado(res) não afetados" -- Needs review
L["Poison"] = "Veneno" -- Needs review
L["Power"] = "Poder" -- Needs review
L["Power (%)"] = "Poder (%)" -- Needs review
L["Power Type"] = "Tipo de poder" -- Needs review
L["Preset"] = "Predefinido" -- Needs review
L["Priest"] = "Sacerdote" -- Needs review
L["Progress"] = "Progresso" -- Needs review
L["Pulse"] = "Pulsar" -- Needs review
L["PvP Flagged"] = "Marcado para JxJ" -- Needs review
L["Radius"] = "Raio" -- Needs review
L["Rage"] = "Raiva" -- Needs review
L["Raid"] = "Raide" -- Needs review
L["Raid Warning"] = "Aviso de raide" -- Needs review
L["Range"] = "Alcance" -- Needs review
L["Ranged"] = "À distância" -- Needs review
-- L["Receiving display information"] = ""
L["Reference Spell"] = "Feitiço referência" -- Needs review
L["Reflect"] = "Refletir" -- Needs review
L["Relative"] = "Relativo" -- Needs review
L["Remaining Time"] = "Tempo restante" -- Needs review
L["Requested display does not exist"] = "Exibição requerida não existe" -- Needs review
L["Requested display not authorized"] = "Exibição requerida não autorizada" -- Needs review
L["Require Valid Target"] = "Requer um alvo válido" -- Needs review
L["Resist"] = "Resistir" -- Needs review
L["Resisted"] = "Resistido" -- Needs review
-- L["Resolve collisions dialog"] = ""
-- L["Resolve collisions dialog singular"] = ""
-- L["Resolve collisions dialog startup"] = ""
-- L["Resolve collisions dialog startup singular"] = ""
L["Resting"] = "Descansando" -- Needs review
L["Resurrect"] = "Reviver" -- Needs review
L["Right"] = "Direita" -- Needs review
L["Right to Left"] = "Da direita à esquerda" -- Needs review
L["Rogue"] = "Ladino" -- Needs review
L["Rotate Left"] = "Girar à esquerda" -- Needs review
L["Rotate Right"] = "Girar à direita" -- Needs review
L["Rune"] = "Runa" -- Needs review
L["Runic Power"] = "Poder rúnico" -- Needs review
L["Say"] = "falar" -- Needs review
L["Seconds"] = "Segundos" -- Needs review
L["Second Tree"] = "Árvore secundária" -- Needs review
L["Shake"] = "Sacudir" -- Needs review
L["Shaman"] = "Xamã" -- Needs review
L["Shards"] = "Fragmentos de alma" -- Needs review
L["Shift-Click to pause"] = "Shift-Click para pausar" -- Needs review
L["Shift-Click to resume"] = "Shift-Click para continuar" -- Needs review
L["Show"] = "Mostrar" -- Needs review
L["Shrink"] = "Encolher" -- Needs review
L["Slide from Bottom"] = "Deslizar de baixo" -- Needs review
L["Slide from Left"] = "Deslizar da esquerda" -- Needs review
L["Slide from Right"] = "Deslizar da direita" -- Needs review
L["Slide from Top"] = "Deslizar de cima" -- Needs review
L["Slide to Bottom"] = "Deslizar para baixo" -- Needs review
L["Slide to Left"] = "Deslizar para esquerda" -- Needs review
L["Slide to Right"] = "Deslizar para direita" -- Needs review
L["Slide to Top"] = "Deslizar para cima" -- Needs review
L["Slime"] = "Lodo" -- Needs review
L["Solar"] = "Solar" -- Needs review
L["Solar Power"] = "Poder solar" -- Needs review
L["Sound Effects"] = "Efeitos sonoros" -- Needs review
L["Source Name"] = "Origem do nome" -- Needs review
L["Source Unit"] = "Origem da unidade" -- Needs review
L["Spacing"] = "Espaçamento" -- Needs review
L["Specific Unit"] = "Unidade específica" -- Needs review
L["Spell"] = "Feitiço" -- Needs review
L["Spell (Building)"] = "Feitiço (Construção)" -- Needs review
L["Spell Name"] = "Nome do feitiço" -- Needs review
L["Spin"] = "Girar" -- Needs review
L["Spiral"] = "Espiral" -- Needs review
L["Spiral In And Out"] = "Espiral dentro e fora" -- Needs review
L["Stacks"] = "Pilhas" -- Needs review
L["Stance/Form/Aura"] = "Postura/Forma/Aura" -- Needs review
L["Status"] = "Estado" -- Needs review
L["Stolen"] = "Roubado" -- Needs review
L["Summon"] = "Invocar" -- Needs review
L["Swing"] = "Balançar" -- Needs review
L["Swing Timer"] = "Tempo de balanço" -- Needs review
L["Talent Specialization"] = "Especialização de talentos" -- Needs review
L["Tank"] = "Tanque" -- Needs review
-- L["Tanking And Highest"] = ""
-- L["Tanking But Not Highest"] = ""
L["Target"] = "Alvo" -- Needs review
-- L["Thick Outline"] = ""
L["Third Tree"] = "Terceira árvore" -- Needs review
L["Threat Situation"] = "Situação de ameaça" -- Needs review
L["Thrown"] = "Arremessar" -- Needs review
L["Timed"] = "Temporizado" -- Needs review
L["Top"] = "Topo" -- Needs review
L["Top Left"] = "Topo à esquerda" -- Needs review
L["Top Right"] = "Topo à direita" -- Needs review
L["Top to Bottom"] = "Do topo para base" -- Needs review
L["Total"] = "Total" -- Needs review
L["Totem"] = "Totem" -- Needs review
L["Totem Name"] = "Nome do totem" -- Needs review
L["Totem Type"] = "Tipo do totem" -- Needs review
L["Transmission error"] = "Erro de transmissão" -- Needs review
L["Trigger:"] = "Gatilho:" -- Needs review
L["Trigger Update"] = "Atualização do gatilho" -- Needs review
L["Undefined"] = "Indefinido" -- Needs review
L["Unholy Rune #1"] = "Runa Profana #1" -- Needs review
L["Unholy Rune #2"] = "Runa Profana #2" -- Needs review
-- L["Unholy Runes"] = ""
L["Unit"] = "Unidade" -- Needs review
L["Unit Characteristics"] = "Características da unidade" -- Needs review
L["Unit Destroyed"] = "Unidade destruída" -- Needs review
L["Unit Died"] = "Unidade morte" -- Needs review
L["Up"] = "Acima" -- Needs review
-- L["Version error recevied higher"] = ""
-- L["Version error recevied lower"] = ""
L["Warlock"] = "Bruxo" -- Needs review
L["Warrior"] = "Guerreiro" -- Needs review
L["Water"] = "Água" -- Needs review
L["WeakAuras"] = "WeakAuras" -- Needs review
L["WeakAurasModelPaths"] = "WeakAuras - Caminhos dos modelos 3D" -- Needs review
L["WeakAurasModelPaths .toc Notes"] = "WeakAurasModelPaths .toc Notas" -- Needs review
L["WeakAurasOptions"] = "Opções do WeakAuras" -- Needs review
L["WeakAurasOptions .toc Notes"] = "WeakAurasOptions .toc Notas" -- Needs review
L["WeakAuras .toc Notes"] = "WeakAuras .toc Notas" -- Needs review
-- L["WeakAurasTutorials"] = ""
-- L["WeakAurasTutorials .toc Notes"] = ""
L["Weapon"] = "Arma" -- Needs review
L["Weapon Enchant"] = "Encantamento de arma" -- Needs review
L["Whisper"] = "Sussurro" -- Needs review
L["Wobble"] = "Oscilar" -- Needs review
L["Yell"] = "Gritar" -- Needs review
L["Zone"] = "Zona" -- Needs review
L["Options/1 Match"] = "1 resultado" -- Needs review
L["Options/Actions"] = "Ações" -- Needs review
L["Options/Activate when the given aura(s) |cFFFF0000can't|r be found"] = "Ativar quando a aura(s) recebida |cFFFF0000não|r for(em) encontra(s)" -- Needs review
L["Options/Add a new display"] = "Adicionar novo display" -- Needs review
L["Options/Add Dynamic Text"] = "Adicionar texto dinâmico" -- Needs review
L["Options/Addon"] = "Addon" -- Needs review
L["Options/Addons"] = "Addons" -- Needs review
L["Options/Add to group %s"] = "Adicionar a um grupo %s" -- Needs review
L["Options/Add to new Dynamic Group"] = "Adicionar a um novo Grupo Dinâmico" -- Needs review
L["Options/Add to new Group"] = "Adicionar a um novo Grupo" -- Needs review
L["Options/Add Trigger"] = "Adicionar Gatilho" -- Needs review
L["Options/A group that dynamically controls the positioning of its children"] = "Um grupo que controla dinamicamente o posicionamentos dos seus elementos" -- Needs review
L["Options/Align"] = "Alinhar" -- Needs review
L["Options/Allow Full Rotation"] = "Habilitar rotação completa" -- Needs review
L["Options/Alpha"] = "Transparência" -- Needs review
L["Options/Anchor"] = "Âncora" -- Needs review
L["Options/Anchor Point"] = "Ponto da âncora" -- Needs review
L["Options/Angle"] = "Ângulo" -- Needs review
L["Options/Animate"] = "Animar" -- Needs review
L["Options/Animated Expand and Collapse"] = "Animação expande e esvai" -- Needs review
-- L["Options/Animation relative duration description"] = ""
L["Options/Animations"] = "Animações" -- Needs review
L["Options/Animation Sequence"] = "Sequência da animação" -- Needs review
L["Options/Aquatic"] = "Aquático" -- Needs review
L["Options/Aura (Paladin)"] = "Aura (Paladino)" -- Needs review
L["Options/Aura(s)"] = "Aura(s)" -- Needs review
L["Options/Auto"] = "Auto" -- Needs review
L["Options/Auto-cloning enabled"] = "Autoclonagem habilitada" -- Needs review
L["Options/Automatic Icon"] = "Ícone automático" -- Needs review
-- L["Options/Backdrop Color"] = ""
-- L["Options/Backdrop Style"] = ""
L["Options/Background"] = "Fundo" -- Needs review
L["Options/Background Color"] = "Cor de fundo" -- Needs review
L["Options/Background Inset"] = "Inserção do fundo" -- Needs review
L["Options/Background Offset"] = "Posicionamento do fundo" -- Needs review
L["Options/Background Texture"] = "Textura do fundo" -- Needs review
L["Options/Bar Alpha"] = "Transparência da barra" -- Needs review
L["Options/Bar Color"] = "Cor da barra" -- Needs review
-- L["Options/Bar Color Settings"] = ""
-- L["Options/Bar in Front"] = ""
L["Options/Bar Texture"] = "Textura da barra" -- Needs review
L["Options/Battle"] = "Luta" -- Needs review
L["Options/Bear"] = "Urso" -- Needs review
-- L["Options/Berserker"] = ""
-- L["Options/Blend Mode"] = ""
L["Options/Blood"] = "Sangue" -- Needs review
L["Options/Border"] = "Borda" -- Needs review
-- L["Options/Border Color"] = ""
-- L["Options/Border Inset"] = ""
L["Options/Border Offset"] = "Posicionamento da borda" -- Needs review
-- L["Options/Border Settings"] = ""
-- L["Options/Border Size"] = ""
-- L["Options/Border Style"] = ""
L["Options/Bottom Text"] = "Texto na base" -- Needs review
L["Options/Button Glow"] = "Iluminar botão" -- Needs review
-- L["Options/Can be a name or a UID (e.g., party1). Only works on friendly players in your group."] = ""
L["Options/Cancel"] = "Cancelar" -- Needs review
L["Options/Cat"] = "Felino" -- Needs review
L["Options/Change the name of this display"] = "Mudar o nome deste display" -- Needs review
L["Options/Channel Number"] = "Número do canal" -- Needs review
L["Options/Check On..."] = "Verificar..." -- Needs review
L["Options/Choose"] = "Escolher" -- Needs review
L["Options/Choose Trigger"] = "Escolher o gatilho" -- Needs review
L["Options/Choose whether the displayed icon is automatic or defined manually"] = "Escolher se o ícone mostrado é automático ou definido manualmente" -- Needs review
-- L["Options/Clone option enabled dialog"] = ""
L["Options/Close"] = "Fechar" -- Needs review
-- L["Options/Collapse"] = ""
-- L["Options/Collapse all loaded displays"] = ""
-- L["Options/Collapse all non-loaded displays"] = ""
L["Options/Color"] = "Cor" -- Needs review
L["Options/Compress"] = "Comprimir" -- Needs review
L["Options/Concentration"] = "Concentração" -- Needs review
L["Options/Constant Factor"] = "Fator constante" -- Needs review
L["Options/Control-click to select multiple displays"] = "Ctrl+clique para selecionar displays múltiplos" -- Needs review
L["Options/Controls the positioning and configuration of multiple displays at the same time"] = "Controla o posicionamento e a configuração de múltiplos displays ao mesmo tempo" -- Needs review
L["Options/Convert to..."] = "Converter para..." -- Needs review
L["Options/Cooldown"] = "Tempo de recarga" -- Needs review
L["Options/Copy"] = "Copiar" -- Needs review
L["Options/Copy settings from..."] = "Copiar as configurações de..." -- Needs review
L["Options/Copy settings from another display"] = "Copiar as configurações de outro mostrador" -- Needs review
L["Options/Copy settings from %s"] = "Copiar configurações de %s" -- Needs review
L["Options/Count"] = "Contar" -- Needs review
L["Options/Creating buttons: "] = "Criando botões:" -- Needs review
L["Options/Creating options: "] = "Criando opções:" -- Needs review
L["Options/Crop X"] = "Cortar X" -- Needs review
L["Options/Crop Y"] = "Cortar Y" -- Needs review
L["Options/Crusader"] = "Cruzado" -- Needs review
L["Options/Custom Code"] = "Código personalizado" -- Needs review
L["Options/Custom Trigger"] = "Gatilho personalizado" -- Needs review
-- L["Options/Custom trigger event tooltip"] = ""
-- L["Options/Custom trigger status tooltip"] = ""
-- L["Options/Custom Untrigger"] = ""
-- L["Options/Custom untrigger event tooltip"] = ""
L["Options/Death"] = "Morte" -- Needs review
L["Options/Death Rune"] = "Runa da morte" -- Needs review
L["Options/Debuff Type"] = "Tipo de penalidade" -- Needs review
L["Options/Defensive"] = "Defensivo" -- Needs review
L["Options/Delete"] = "Apagar" -- Needs review
L["Options/Delete all"] = "Apagar tudo" -- Needs review
L["Options/Delete children and group"] = "Apagar as crianças e o grupo" -- Needs review
L["Options/Deletes this display - |cFF8080FFShift|r must be held down while clicking"] = "Apagar este painel" -- Needs review
L["Options/Delete Trigger"] = "Apagar gatilho" -- Needs review
L["Options/Desaturate"] = "Descolorir" -- Needs review
L["Options/Devotion"] = "Devoção" -- Needs review
L["Options/Disabled"] = "Desabilitar" -- Needs review
L["Options/Discrete Rotation"] = "Rotação discreta" -- Needs review
L["Options/Display"] = "Mostruário" -- Needs review
L["Options/Display Icon"] = "Ícone do mostruário" -- Needs review
L["Options/Display Text"] = "Texto do mostruário" -- Needs review
L["Options/Distribute Horizontally"] = "Distribuir horizontalmente" -- Needs review
L["Options/Distribute Vertically"] = "Distribuir verticalmente" -- Needs review
L["Options/Do not copy any settings"] = "Não copie qualquer configuração" -- Needs review
L["Options/Do not group this display"] = "Não agrupe este mostruário" -- Needs review
L["Options/Duplicate"] = "Duplicar" -- Needs review
L["Options/Duration Info"] = "Informação da duração" -- Needs review
L["Options/Duration (s)"] = "Duração" -- Needs review
L["Options/Dynamic Group"] = "Grupo dinâmico" -- Needs review
-- L["Options/Dynamic text tooltip"] = ""
L["Options/Enabled"] = "Habilitado" -- Needs review
L["Options/Enter an aura name, partial aura name, or spell id"] = "Entre um nome de aura, uma parte do nome da aura, ou id do feitiço" -- Needs review
L["Options/Event Type"] = "Tipo de evento" -- Needs review
L["Options/Expand"] = "Expandir" -- Needs review
L["Options/Expand all loaded displays"] = "Expandir todos os mostruários carregados" -- Needs review
L["Options/Expand all non-loaded displays"] = "Expandir todos os mostruários não carregados" -- Needs review
L["Options/Expand Text Editor"] = "Expandir o editor de texto" -- Needs review
L["Options/Expansion is disabled because this group has no children"] = "A expansão está desabilitada porque este grupo não tem nenhuma criança" -- Needs review
L["Options/Export"] = "Exportar" -- Needs review
L["Options/Export to Lua table..."] = "Exportar para tabela Lua" -- Needs review
L["Options/Export to string..."] = "Exportar para uma string" -- Needs review
L["Options/Fade"] = "Sumir" -- Needs review
L["Options/Finish"] = "Finalizar" -- Needs review
L["Options/Fire Resistance"] = "Resistência ao fogo" -- Needs review
L["Options/Flight(Non-Feral)"] = "Luta(não-fera)" -- Needs review
L["Options/Font"] = "Fonte" -- Needs review
-- L["Options/Font Flags"] = ""
-- L["Options/Font Size"] = ""
-- L["Options/Font Type"] = ""
L["Options/Foreground Color"] = "Cor do primeiro plano" -- Needs review
L["Options/Foreground Texture"] = "Textura do primeiro plano" -- Needs review
L["Options/Form (Druid)"] = "Forma" -- Needs review
L["Options/Form (Priest)"] = "Forma" -- Needs review
L["Options/Form (Shaman)"] = "Forma" -- Needs review
L["Options/Form (Warlock)"] = "Forma" -- Needs review
L["Options/Frame"] = "Quadro" -- Needs review
L["Options/Frame Strata"] = "Camada do quadro" -- Needs review
L["Options/Frost"] = "Gélido" -- Needs review
L["Options/Frost Resistance"] = "Resistência ao gélido" -- Needs review
L["Options/Full Scan"] = "Escaneamento completo" -- Needs review
L["Options/Ghost Wolf"] = "Lobo fantasma" -- Needs review
L["Options/Glow Action"] = "Ação incandescente" -- Needs review
-- L["Options/Group aura count description"] = ""
L["Options/Group Member Count"] = "Contagem dos membros do grupo" -- Needs review
L["Options/Group (verb)"] = "Agrupar" -- Needs review
L["Options/Height"] = "Altura" -- Needs review
L["Options/Hide this group's children"] = "Esconder as crianças deste grupo" -- Needs review
L["Options/Hide When Not In Group"] = "Esconder quando em grupo" -- Needs review
L["Options/Horizontal Align"] = "Alinhamento horizontal" -- Needs review
L["Options/Icon Info"] = "Informação do ícone" -- Needs review
L["Options/Ignored"] = "Ignorado" -- Needs review
L["Options/Ignore GCD"] = "Ignorar GCD" -- Needs review
L["Options/%i Matches"] = "%i resultados" -- Needs review
L["Options/Import"] = "Importar" -- Needs review
L["Options/Import a display from an encoded string"] = "Importar um display de um string codificado" -- Needs review
L["Options/Justify"] = "Justificar" -- Needs review
L["Options/Left Text"] = "Texto à esquerda" -- Needs review
-- L["Options/Load"] = ""
L["Options/Loaded"] = "Carrregar" -- Needs review
L["Options/Main"] = "Principal" -- Needs review
L["Options/Main Trigger"] = "Gatilho principal" -- Needs review
L["Options/Mana (%)"] = "Mana (%)" -- Needs review
L["Options/Manage displays defined by Addons"] = "Gerencia os displays definidos por addons" -- Needs review
L["Options/Message Prefix"] = "Prefixo de mensagem" -- Needs review
L["Options/Message Suffix"] = "Sufixo de mensagem" -- Needs review
L["Options/Metamorphosis"] = "Metamorfose" -- Needs review
L["Options/Mirror"] = "Espelho" -- Needs review
L["Options/Model"] = "Modelo" -- Needs review
L["Options/Moonkin/Tree/Flight(Feral)"] = "Moonkin/Árvore/Vôo(Feral)" -- Needs review
L["Options/Move Down"] = "Mover para baixo" -- Needs review
L["Options/Move this display down in its group's order"] = "Move este display para baixo no ordenamento do seu grupo" -- Needs review
L["Options/Move this display up in its group's order"] = "Move este display para cima no ordenamento do seu grupo" -- Needs review
L["Options/Move Up"] = "Mover para cima" -- Needs review
L["Options/Multiple Displays"] = "Múltiplos displays" -- Needs review
L["Options/Multiple Triggers"] = "Múltiplos gatilhos" -- Needs review
-- L["Options/Multiselect ignored tooltip"] = ""
-- L["Options/Multiselect multiple tooltip"] = ""
-- L["Options/Multiselect single tooltip"] = ""
L["Options/Must be spelled correctly!"] = "Deve ser soletrado corretamente!" -- Needs review
L["Options/Name Info"] = "Informação do nome" -- Needs review
L["Options/Negator"] = "Negador" -- Needs review
L["Options/New"] = "Novo" -- Needs review
L["Options/Next"] = "Próximo" -- Needs review
L["Options/No"] = "Não" -- Needs review
-- L["Options/No Children"] = ""
-- L["Options/Not all children have the same value for this option"] = ""
L["Options/Not Loaded"] = "Não carregado" -- Needs review
-- L["Options/No tooltip text"] = ""
L["Options/% of Progress"] = "% do progresso" -- Needs review
L["Options/Okay"] = "Okay" -- Needs review
L["Options/On Hide"] = "Quando sumir" -- Needs review
-- L["Options/Only match auras cast by people other than the player"] = ""
-- L["Options/Only match auras cast by the player"] = ""
L["Options/On Show"] = "Quando mostrar" -- Needs review
L["Options/Operator"] = "Operador" -- Needs review
-- L["Options/or"] = ""
L["Options/Orientation"] = "Orientação" -- Needs review
L["Options/Other"] = "Outro" -- Needs review
L["Options/Outline"] = "Contorno" -- Needs review
L["Options/Own Only"] = "Apenas meu" -- Needs review
L["Options/Player Character"] = "Personagem do jogador" -- Needs review
L["Options/Play Sound"] = "Reproduzir som" -- Needs review
L["Options/Presence (DK)"] = "Presença (CM)" -- Needs review
L["Options/Presence (Rogue)"] = "Presença (Ladino)" -- Needs review
-- L["Options/Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = ""
L["Options/Primary"] = "Primário" -- Needs review
L["Options/Progress Bar"] = "Barra de progresso" -- Needs review
L["Options/Progress Texture"] = "Textura de progresso" -- Needs review
L["Options/Put this display in a group"] = "Colocar este display em um grupo" -- Needs review
L["Options/Ready For Use"] = "Pronto para uso" -- Needs review
L["Options/Re-center X"] = "Recentralizar X" -- Needs review
L["Options/Re-center Y"] = "Recentralizar Y" -- Needs review
L["Options/Remaining Time Precision"] = "Precisão do tempo restante" -- Needs review
L["Options/Remove this display from its group"] = "Remover este display de um grupo" -- Needs review
L["Options/Rename"] = "Renomear" -- Needs review
L["Options/Requesting display information"] = "Solicitando informações do display de %s..." -- Needs review
L["Options/Required For Activation"] = "Requerido para ativar" -- Needs review
L["Options/Retribution"] = "Retribuição" -- Needs review
L["Options/Right-click for more options"] = "Clique-direito para mais opções" -- Needs review
L["Options/Right Text"] = "Texto à direita" -- Needs review
L["Options/Rotate"] = "Girar" -- Needs review
L["Options/Rotate In"] = "Girar para dentro" -- Needs review
L["Options/Rotate Out"] = "Girar para fora" -- Needs review
L["Options/Rotate Text"] = "Girar o texto" -- Needs review
L["Options/Rotation"] = "Rotação" -- Needs review
L["Options/Same"] = "Mesmo" -- Needs review
L["Options/Search"] = "Procurar" -- Needs review
L["Options/Secondary"] = "Secundário" -- Needs review
L["Options/Send To"] = "Enviar para" -- Needs review
-- L["Options/Set tooltip description"] = ""
L["Options/Shadow Dance"] = "Dança das sombras" -- Needs review
L["Options/Shadowform"] = "Forma de sombra" -- Needs review
L["Options/Shadow Resistance"] = "Resistência às sombras" -- Needs review
L["Options/Shift-click to create chat link"] = "Shift-clique para criar um link na conversa" -- Needs review
L["Options/Show all matches (Auto-clone)"] = "Mostrar todas as correspondências" -- Needs review
L["Options/Show players that are |cFFFF0000not affected"] = "Mostrar todos os jogadores que |cFFFF0000não foram afetados" -- Needs review
L["Options/Shows a 3D model from the game files"] = "Mostrar um modelo 3D dos arquivos do jogo" -- Needs review
L["Options/Shows a custom texture"] = "Mostrar uma textura personalizada" -- Needs review
L["Options/Shows a progress bar with name, timer, and icon"] = "Mostrar uma barra de progresso com nome, temporizador e ícone" -- Needs review
L["Options/Shows a spell icon with an optional a cooldown overlay"] = "Mostrar um ícone de feitiço com o opcional do tempo de recarga sobreposto" -- Needs review
L["Options/Shows a texture that changes based on duration"] = "Mostrar uma textura que muda com base na duração" -- Needs review
L["Options/Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = "Mostra uma ou mais linhas de texto, que podem incluir informações dinâmicas tal como progresso ou quantidades" -- Needs review
L["Options/Shows the remaining or expended time for an aura or timed event"] = "Mostra o tempo restante ou expedido de uma aura ou evento cronometrado" -- Needs review
-- L["Options/Show this group's children"] = ""
L["Options/Size"] = "Tamanho" -- Needs review
L["Options/Slide"] = "Deslizar" -- Needs review
L["Options/Slide In"] = "Deslizar para dentro" -- Needs review
L["Options/Slide Out"] = "Deslizar para fora" -- Needs review
L["Options/Sort"] = "Ordenar" -- Needs review
L["Options/Sound"] = "Som" -- Needs review
L["Options/Sound Channel"] = "Canal de som" -- Needs review
L["Options/Sound File Path"] = "Caminho do arquivo de som" -- Needs review
L["Options/Space"] = "Espaço" -- Needs review
L["Options/Space Horizontally"] = "Espaço horizontal" -- Needs review
-- L["Options/Space Vertically"] = ""
-- L["Options/Spell ID"] = ""
-- L["Options/Spell ID dialog"] = ""
-- L["Options/Stack Count"] = ""
-- L["Options/Stack Count Position"] = ""
-- L["Options/Stack Info"] = ""
-- L["Options/Stacks Settings"] = ""
-- L["Options/Stagger"] = ""
-- L["Options/Stance (Warrior)"] = ""
-- L["Options/Start"] = ""
-- L["Options/Stealable"] = ""
-- L["Options/Stealthed"] = ""
-- L["Options/Sticky Duration"] = ""
-- L["Options/Temporary Group"] = ""
-- L["Options/Text"] = ""
-- L["Options/Text Color"] = ""
-- L["Options/Text Position"] = ""
-- L["Options/Text Settings"] = ""
-- L["Options/Texture"] = ""
-- L["Options/The children of this group have different display types, so their display options cannot be set as a group."] = ""
-- L["Options/The duration of the animation in seconds."] = ""
-- L["Options/The type of trigger"] = ""
-- L["Options/This condition will not be tested"] = ""
-- L["Options/This display is currently loaded"] = ""
-- L["Options/This display is not currently loaded"] = ""
-- L["Options/This display will only show when |cFF00FF00%s"] = ""
-- L["Options/This display will only show when |cFFFF0000 Not %s"] = ""
-- L["Options/This region of type \"%s\" has no configuration options."] = ""
-- L["Options/Time in"] = ""
-- L["Options/Timer"] = ""
-- L["Options/Timer Settings"] = ""
-- L["Options/Toggle the visibility of all loaded displays"] = ""
-- L["Options/Toggle the visibility of all non-loaded displays"] = ""
-- L["Options/Toggle the visibility of this display"] = ""
-- L["Options/to group's"] = ""
-- L["Options/Tooltip"] = ""
-- L["Options/Tooltip on Mouseover"] = ""
-- L["Options/Top Text"] = ""
-- L["Options/to screen's"] = ""
-- L["Options/Total Time Precision"] = ""
-- L["Options/Tracking"] = ""
-- L["Options/Travel"] = ""
-- L["Options/Trigger"] = ""
-- L["Options/Trigger %d"] = ""
-- L["Options/Triggers"] = ""
-- L["Options/Type"] = ""
-- L["Options/Ungroup"] = ""
-- L["Options/Unholy"] = ""
-- L["Options/Unit Exists"] = ""
-- L["Options/Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = ""
-- L["Options/Unstealthed"] = ""
-- L["Options/Update Custom Text On..."] = ""
-- L["Options/Use Full Scan (High CPU)"] = ""
-- L["Options/Use tooltip \"size\" instead of stacks"] = ""
-- L["Options/Vertical Align"] = ""
-- L["Options/View"] = ""
-- L["Options/Width"] = ""
-- L["Options/X Offset"] = ""
-- L["Options/X Scale"] = ""
-- L["Options/Yes"] = ""
-- L["Options/Y Offset"] = ""
-- L["Options/Y Scale"] = ""
-- L["Options/Z Offset"] = ""
-- L["Options/Zoom"] = ""
-- L["Options/Zoom In"] = ""
-- L["Options/Zoom Out"] = ""
-- L["Tutorials/Actions and Animations: 1/7"] = ""
-- L["Tutorials/Actions and Animations: 2/7"] = ""
-- L["Tutorials/Actions and Animations: 3/7"] = ""
-- L["Tutorials/Actions and Animations: 4/7"] = ""
-- L["Tutorials/Actions and Animations: 5/7"] = ""
-- L["Tutorials/Actions and Animations: 6/7"] = ""
-- L["Tutorials/Actions and Animations: 7/7"] = ""
-- L["Tutorials/Actions and Animations Text"] = ""
-- L["Tutorials/Activation Settings: 1/5"] = ""
-- L["Tutorials/Activation Settings: 2/5"] = ""
-- L["Tutorials/Activation Settings: 3/5"] = ""
-- L["Tutorials/Activation Settings: 4/5"] = ""
-- L["Tutorials/Activation Settings: 5/5"] = ""
-- L["Tutorials/Activation Settings Text"] = ""
-- L["Tutorials/Auto-cloning: 1/10"] = ""
-- L["Tutorials/Auto-cloning 1/10 Text"] = ""
-- L["Tutorials/Beginners Finished Text"] = ""
-- L["Tutorials/Beginners Guide Desc"] = ""
-- L["Tutorials/Beginners Guide Desc Text"] = ""
-- L["Tutorials/Create a Display: 1/5"] = ""
-- L["Tutorials/Create a Display: 2/5"] = ""
-- L["Tutorials/Create a Display: 3/5"] = ""
-- L["Tutorials/Create a Display: 4/5"] = ""
-- L["Tutorials/Create a Display: 5/5"] = ""
-- L["Tutorials/Create a Display Text"] = ""
-- L["Tutorials/Display Options: 1/4"] = ""
-- L["Tutorials/Display Options 1/4 Text"] = ""
-- L["Tutorials/Display Options: 2/4"] = ""
-- L["Tutorials/Display Options 2/4 Text"] = ""
-- L["Tutorials/Display Options: 4/4"] = ""
-- L["Tutorials/Display Options 4/4 Text"] = ""
-- L["Tutorials/Dynamic Group Options: 2/4"] = ""
-- L["Tutorials/Dynamic Group Options 2/4 Text"] = ""
-- L["Tutorials/Dynamic Group Options: 3/4"] = ""
-- L["Tutorials/Dynamic Group Options 3/4 Text"] = ""
-- L["Tutorials/Dynamic Group Options: 4/4"] = ""
-- L["Tutorials/Dynamic Group Options 4/4 Text"] = ""
-- L["Tutorials/Finished"] = ""
-- L["Tutorials/Full-scan Auras: 2/10"] = ""
-- L["Tutorials/Full-scan Auras 2/10 Text"] = ""
-- L["Tutorials/Full-scan Auras: 3/10"] = ""
-- L["Tutorials/Full-scan Auras 3/10 Text"] = ""
-- L["Tutorials/Full-scan Auras: 4/10"] = ""
-- L["Tutorials/Full-scan Auras 4/10 Text"] = ""
-- L["Tutorials/Full-scan Auras: 5/10"] = ""
-- L["Tutorials/Full-scan Auras 5/10 Text"] = ""
-- L["Tutorials/Group Auras 6/10"] = ""
-- L["Tutorials/Group Auras 6/10 Text"] = ""
-- L["Tutorials/Group Auras: 7/10"] = ""
-- L["Tutorials/Group Auras 7/10 Text"] = ""
-- L["Tutorials/Group Auras: 8/10"] = ""
-- L["Tutorials/Group Auras 8/10 Text"] = ""
-- L["Tutorials/Home"] = ""
-- L["Tutorials/Multi-target Auras: 10/10"] = ""
-- L["Tutorials/Multi-target Auras 10/10 Text"] = ""
-- L["Tutorials/Multi-target Auras: 9/10"] = ""
-- L["Tutorials/Multi-target Auras 9/10 Text"] = ""
-- L["Tutorials/New in 1.4:"] = ""
-- L["Tutorials/New in 1.4 Desc:"] = ""
-- L["Tutorials/New in 1.4 Desc Text"] = ""
-- L["Tutorials/New in 1.4 Finnished Text"] = ""
-- L["Tutorials/New in 1.4 Text1"] = ""
-- L["Tutorials/New in 1.4 Text2"] = ""
-- L["Tutorials/Previous"] = ""
-- L["Tutorials/Trigger Options: 1/4"] = ""
-- L["Tutorials/Trigger Options 1/4 Text"] = ""
-- L["Tutorials/Trigger Options: 2/4"] = ""
-- L["Tutorials/Trigger Options 2/4 Text"] = ""
-- L["Tutorials/Trigger Options: 3/4"] = ""
-- L["Tutorials/Trigger Options 3/4 Text"] = ""
-- L["Tutorials/Trigger Options: 4/4"] = ""
-- L["Tutorials/Trigger Options 4/4 Text"] = ""
-- L["Tutorials/WeakAuras Tutorials"] = ""
-- L["Tutorials/Welcome"] = ""
-- L["Tutorials/Welcome Text"] = ""



