if not(GetLocale() == "koKR") then
    return;
end

local L = WeakAuras.L

-- Options translation
L["<"] = "<" -- Needs review
L["<="] = "<=" -- Needs review
L["="] = "=" -- Needs review
L[">"] = ">" -- Needs review
L[">="] = ">=" -- Needs review
L["!="] = "!=" -- Needs review
L["10 Man Raid"] = "10인 공격대" -- Needs review
L["25 Man Raid"] = "25인 공격대" -- Needs review
L["5 Man Dungeon"] = "5인 던전" -- Needs review
L["Absorb"] = "흡수" -- Needs review
L["Absorbed"] = "흡수됨" -- Needs review
L["Action Usable"] = "사용 가능" -- Needs review
-- L["Affected"] = ""
-- L["Air"] = ""
-- L["Alive"] = ""
L["All Triggers"] = "모든 조건" -- Needs review
-- L["Alternate Power"] = ""
-- L["Ambience"] = ""
-- L["Amount"] = ""
L["Any Triggers"] = "아무 조건" -- Needs review
L["Arena"] = "투기장" -- Needs review
L["Ascending"] = "올림차순" -- Needs review
L["At Least One Enemy"] = "최소 1명의 적 대상" -- Needs review
L["Attackable"] = "공격 가능" -- Needs review
L["Aura"] = "오라" -- Needs review
L["Aura:"] = "오라:" -- Needs review
L["Aura Applied"] = "오라 적용됨" -- Needs review
-- L["Aura Applied Dose"] = ""
-- L["Aura Broken"] = ""
-- L["Aura Broken Spell"] = ""
L["Aura Name"] = "오라 이름" -- Needs review
-- L["Aura Refresh"] = ""
L["Aura Removed"] = "오라 사라짐" -- Needs review
-- L["Aura Removed Dose"] = ""
L["Auras:"] = "오라:" -- Needs review
L["Aura Stack"] = "오라 중첩" -- Needs review
L["Aura Type"] = "오라 종류" -- Needs review
L["Automatic"] = "자동" -- Needs review
-- L["Back and Forth"] = ""
L["Battleground"] = "전장" -- Needs review
L["Battle.net Whisper"] = "실명 ID 귓속말" -- Needs review
L["BG>Raid>Party>Say"] = "전장>공격대>파티>일반대화" -- Needs review
L["BG-System Alliance"] = "전장 얼라이언스" -- Needs review
L["BG-System Horde"] = "전장 호드" -- Needs review
L["BG-System Neutral"] = "전장 중립" -- Needs review
L["Blizzard Combat Text"] = "블리자드 전투메세지" -- Needs review
L["Block"] = "방어" -- Needs review
L["Blocked"] = "방어" -- Needs review
L["Blood Rune #1"] = "혈기 룬 #1" -- Needs review
L["Blood Rune #2"] = "혈기 룬 #2" -- Needs review
L["Blood runes"] = "혈기 룬" -- Needs review
L["Boss Emote"] = "보스 감정표현" -- Needs review
L["Bottom"] = "아래" -- Needs review
L["Bottom Left"] = "왼쪽 아래" -- Needs review
L["Bottom Right"] = "오른쪽 아래" -- Needs review
L["Bottom to Top"] = "아래에서 위로" -- Needs review
L["Bounce"] = "바운스" -- Needs review
-- L["Bounce with Decay"] = ""
L["Buff"] = "버프" -- Needs review
L["By |cFF69CCF0Mirrored|r of Dragonmaw(US) Horde"] = "By |cFF69CCF0Mirrored|r of Dragonmaw서버 (US) 호드" -- Needs review
L["Cast"] = "시전" -- Needs review
L["Cast Failed"] = "시전 실패" -- Needs review
L["Cast Start"] = "시전 시작" -- Needs review
L["Cast Success"] = "시전 성공" -- Needs review
L["Cast Type"] = "시전 종류" -- Needs review
L["Center"] = "중앙" -- Needs review
L["Centered Horizontal"] = "수평 중앙" -- Needs review
L["Centered Vertical"] = "수직 중앙" -- Needs review
L["Channel"] = "채널" -- Needs review
L["Channel (Spell)"] = "채널" -- Needs review
L["Character Type"] = "캐릭터 종류" -- Needs review
L["Chat Frame"] = "채팅창" -- Needs review
L["Chat Message"] = "채팅 메세지" -- Needs review
-- L["Children:"] = ""
-- L["Circle"] = ""
-- L["Circular"] = ""
L["Class"] = "직업" -- Needs review
L["Click to close configuration"] = "클릭 - 설정창을 닫습니다" -- Needs review
L["Click to open configuration"] = "클릭 - 설정창 열기" -- Needs review
L["Combat Log"] = "전투메시지 기록" -- Needs review
L["Combo Points"] = "연계 점수" -- Needs review
-- L["Conditions"] = ""
-- L["Contains"] = ""
L["Cooldown Progress (Item)"] = "쿨다운 진행상황 (아이템)" -- Needs review
L["Cooldown Progress (Spell)"] = "쿨다운 진행상황 (주문)" -- Needs review
L["Cooldown Ready (Item)"] = "쿨다운 준비됨 (아이템)" -- Needs review
L["Cooldown Ready (Spell)"] = "쿨다운 준비됨 (주문)" -- Needs review
L["Create"] = "생성" -- Needs review
L["Critical"] = "치명타" -- Needs review
L["Crowd Controlled"] = "군중 제어" -- Needs review
-- L["Crushing"] = ""
L["Curse"] = "저주" -- Needs review
L["Custom"] = "개인추가" -- Needs review
L["Custom Function"] = "개인추가 기능" -- Needs review
L["Damage"] = "피해" -- Needs review
-- L["Damager"] = ""
L["Damage Shield"] = "피해 흡수" -- Needs review
-- L["Damage Shield Missed"] = ""
-- L["Damage Split"] = ""
L["Death Knight"] = "죽음의 기사" -- Needs review
L["Death Knight Rune"] = "죽음의 기사 룬" -- Needs review
-- L["Death Rune"] = ""
L["Debuff"] = "디버프" -- Needs review
L["Deflect"] = "튕김" -- Needs review
L["Descending"] = "내림차순" -- Needs review
L["Destination Name"] = "대상 이름" -- Needs review
L["Destination Unit"] = "대상 유닛" -- Needs review
L["Disease"] = "질병" -- Needs review
L["Dispel"] = "해제" -- Needs review
L["Dispel Failed"] = "해제 실패" -- Needs review
L["Dodge"] = "회피" -- Needs review
L["Done"] = "완료" -- Needs review
L["Down"] = "아래로" -- Needs review
-- L["Drain"] = ""
-- L["Drowning"] = ""
L["Druid"] = "드루이드" -- Needs review
L["Dungeon Difficulty"] = "던전 난이도" -- Needs review
-- L["Durability Damage"] = ""
-- L["Durability Damage All"] = ""
-- L["Earth"] = ""
-- L["Eclipse Direction"] = ""
L["Eclipse Power"] = "일식/월식 파워" -- Needs review
L["Eclipse Type"] = "일식/월식 유형" -- Needs review
L["Emote"] = "감정표현" -- Needs review
-- L["Energize"] = ""
L["Energy"] = "기력" -- Needs review
-- L["Enrage"] = ""
-- L["Environmental"] = ""
L["Environment Type"] = "환경 종류" -- Needs review
L["Evade"] = "벗어남" -- Needs review
L["Event"] = "이벤트" -- Needs review
L["Event(s)"] = "이벤트" -- Needs review
L["Every Frame"] = "매 프레임" -- Needs review
-- L["Extra Amount"] = ""
-- L["Extra Attacks"] = ""
-- L["Extra Spell Name"] = ""
L["Fade In"] = "서서히 나타남" -- Needs review
L["Fade Out"] = "서서히 사라짐" -- Needs review
-- L["Falling"] = ""
-- L["Fatigue"] = ""
-- L["Fire"] = ""
-- L["First Tree"] = ""
L["Flash"] = "반짝임" -- Needs review
L["Flip"] = "던지기" -- Needs review
L["Focus"] = "주시" -- Needs review
L["Form"] = "폼" -- Needs review
L["Friendly"] = "우호적 대상" -- Needs review
-- L["From"] = ""
L["Frost Rune #1"] = "냉기 룬 #1" -- Needs review
L["Frost Rune #2"] = "냉기 룬 #2" -- Needs review
L["Frost Runes"] = "냉기 룬" -- Needs review
L["Glancing"] = "비껴맞음" -- Needs review
L["Global Cooldown"] = "글로벌 쿨다운" -- Needs review
L["Glow"] = "빛남" -- Needs review
L["Gradient"] = "그라디언트" -- Needs review
-- L["Gradient Pulse"] = ""
L["Group"] = "그룹" -- Needs review
L["Group %s"] = "그룹 %s" -- Needs review
L["Grow"] = "성장" -- Needs review
L["Guild"] = "길드" -- Needs review
L["Happiness"] = "만족도" -- Needs review
L["HasPet"] = "소환수 있음 (살아있음)" -- Needs review
L["Heal"] = "힐" -- Needs review
L["Healer"] = "힐러" -- Needs review
L["Health"] = "체력" -- Needs review
L["Health (%)"] = "체력 (%)" -- Needs review
L["Heroic"] = "영웅" -- Needs review
L["Hide"] = "숨김" -- Needs review
-- L["Higher Than Tank"] = ""
L["Holy Power"] = "신성한 힘" -- Needs review
L["Hostile"] = "적 대상" -- Needs review
-- L["Hostility"] = ""
L["Humanoid"] = "인간형" -- Needs review
L["Hunter"] = "사냥꾼" -- Needs review
L["Icon"] = "아이콘" -- Needs review
L["Ignore Rune CD"] = "룬 쿨다운 무시" -- Needs review
L["Immune"] = "면역" -- Needs review
L["Include Bank"] = "은행 포함" -- Needs review
-- L["Include Charges"] = ""
-- L["Include Death Runes"] = ""
L["In Combat"] = "전투중" -- Needs review
L["Inherited"] = "상속" -- Needs review
L["Inside"] = "안쪽" -- Needs review
-- L["Instakill"] = ""
L["Instance Type"] = "인스턴스 종류" -- Needs review
L["Interrupt"] = "차단" -- Needs review
L["Interruptible"] = "차단 가능" -- Needs review
L["In Vehicle"] = "탑승중" -- Needs review
L["Inverse"] = "반대로" -- Needs review
L["Is Exactly"] = "정확함" -- Needs review
L["Item"] = "아이템" -- Needs review
L["Item Count"] = "아이템 갯수" -- Needs review
L["Item Equipped"] = "아이템 착용됨" -- Needs review
-- L["Lava"] = ""
-- L["Leech"] = ""
L["Left"] = "왼쪽" -- Needs review
L["Left to Right"] = "왼쪽에서 오른쪽" -- Needs review
L["Level"] = "레벨" -- Needs review
-- L["Lower Than Tank"] = ""
-- L["Lunar"] = ""
-- L["Lunar Power"] = ""
L["Mage"] = "마법사" -- Needs review
L["Magic"] = "마법" -- Needs review
L["Main Hand"] = "주무기" -- Needs review
L["Mana"] = "마나" -- Needs review
-- L["Master"] = ""
-- L["Matches (Pattern)"] = ""
L["Message"] = "메세지" -- Needs review
L["Message type:"] = "메세지 유형:" -- Needs review
L["Message Type"] = "메세지 유형" -- Needs review
-- L["Miss"] = ""
L["Missed"] = "빗나감" -- Needs review
-- L["Missing"] = ""
-- L["Miss Type"] = ""
L["Monochrome"] = "단색" -- Needs review
-- L["Monster Yell"] = ""
-- L["Mounted"] = ""
L["Multi-target"] = "다중 대상" -- Needs review
L["Music"] = "음악" -- Needs review
L["Name"] = "이름" -- Needs review
-- L["Never"] = ""
L["Next"] = "다음" -- Needs review
-- L["No Children:"] = ""
-- L["No Instance"] = ""
L["None"] = "없음" -- Needs review
L["Non-player Character"] = "NPC" -- Needs review
L["Normal"] = "일반" -- Needs review
-- L["Not On Threat Table"] = ""
-- L["Number"] = ""
-- L["Number Affected"] = ""
L["Off Hand"] = "보조무기" -- Needs review
L["Officer"] = "길드관리자" -- Needs review
L["Opaque"] = "불투명" -- Needs review
L["Orbit"] = "공전" -- Needs review
L["Outline"] = "외곽선" -- Needs review
L["Outside"] = "바깥쪽" -- Needs review
L["Overhealing"] = "초과치유" -- Needs review
-- L["Overkill"] = ""
L["Paladin"] = "성기사" -- Needs review
L["Parry"] = "막음" -- Needs review
L["Party"] = "파티" -- Needs review
-- L["Party Kill"] = ""
L["Paused"] = "일시정지됨" -- Needs review
L["Periodic Spell"] = "주기적인 주문" -- Needs review
L["Pet"] = "소환수" -- Needs review
L["Player"] = "플레이어" -- Needs review
L["Player Character"] = "플레이어 캐릭터" -- Needs review
L["Player Class"] = "플레이어 직업" -- Needs review
L["Player Dungeon Role"] = "플레이어 던전 역할" -- Needs review
L["Player Level"] = "플레이어 레벨" -- Needs review
L["Player Name"] = "플레이어 이름" -- Needs review
-- L["Player(s) Affected"] = ""
-- L["Player(s) Not Affected"] = ""
L["Poison"] = "독" -- Needs review
L["Power"] = "파워" -- Needs review
L["Power (%)"] = "파워 (%)" -- Needs review
L["Power Type"] = "파워 유형" -- Needs review
L["Preset"] = "프리셋" -- Needs review
L["Priest"] = "사제" -- Needs review
L["Progress"] = "진행" -- Needs review
-- L["Pulse"] = ""
-- L["PvP Flagged"] = ""
-- L["Radius"] = ""
L["Rage"] = "분노" -- Needs review
L["Raid"] = "공격대" -- Needs review
L["Raid Warning"] = "공격대 경보" -- Needs review
-- L["Range"] = ""
-- L["Ranged"] = ""
L["Receiving display information"] = "%s에서 디스플레이 정보 수신 중..." -- Needs review
-- L["Reference Spell"] = ""
L["Reflect"] = "반사" -- Needs review
-- L["Relative"] = ""
L["Remaining Time"] = "남은 시간" -- Needs review
-- L["Requested display does not exist"] = ""
-- L["Requested display not authorized"] = ""
L["Require Valid Target"] = "유효 대상 필요" -- Needs review
L["Resist"] = "저항" -- Needs review
L["Resisted"] = "저항" -- Needs review
-- L["Resolve collisions dialog"] = ""
-- L["Resolve collisions dialog singular"] = ""
-- L["Resolve collisions dialog startup"] = ""
-- L["Resolve collisions dialog startup singular"] = ""
L["Resting"] = "휴식중" -- Needs review
L["Resurrect"] = "부활" -- Needs review
L["Right"] = "오른쪽" -- Needs review
L["Right to Left"] = "오른쪽에서 왼쪽" -- Needs review
L["Rogue"] = "도적" -- Needs review
L["Rotate Left"] = "왼쪽으로 회전" -- Needs review
L["Rotate Right"] = "오른쪽으로 회전" -- Needs review
L["Rune"] = "룬" -- Needs review
L["Runic Power"] = "룬마력" -- Needs review
L["Say"] = "일반대화" -- Needs review
L["Seconds"] = "초" -- Needs review
-- L["Second Tree"] = ""
L["Shake"] = "흔들기" -- Needs review
L["Shaman"] = "주술사" -- Needs review
L["Shards"] = "조각" -- Needs review
L["Shift-Click to pause"] = "Shift-Click - 일시정지" -- Needs review
L["Shift-Click to resume"] = "Shift-Click - 재시작" -- Needs review
L["Show"] = "보이기" -- Needs review
L["Shrink"] = "축소" -- Needs review
-- L["Slide from Bottom"] = ""
-- L["Slide from Left"] = ""
-- L["Slide from Right"] = ""
-- L["Slide from Top"] = ""
-- L["Slide to Bottom"] = ""
-- L["Slide to Left"] = ""
-- L["Slide to Right"] = ""
-- L["Slide to Top"] = ""
-- L["Slime"] = ""
-- L["Solar"] = ""
-- L["Solar Power"] = ""
L["Sound Effects"] = "사운드 효과" -- Needs review
L["Source Name"] = "시전자 이름" -- Needs review
L["Source Unit"] = "시전자 유닛" -- Needs review
L["Spacing"] = "간격" -- Needs review
L["Specific Unit"] = "특정 유닛" -- Needs review
L["Spell"] = "주문" -- Needs review
-- L["Spell (Building)"] = ""
L["Spell Name"] = "주문 이름" -- Needs review
L["Spin"] = "회전" -- Needs review
L["Spiral"] = "소용돌이" -- Needs review
-- L["Spiral In And Out"] = ""
-- L["Stacks"] = ""
L["Stance/Form/Aura"] = "태세/폼/오라" -- Needs review
L["Status"] = "상태" -- Needs review
L["Stolen"] = "훔치기" -- Needs review
L["Summon"] = "소환" -- Needs review
L["Swing"] = "스윙" -- Needs review
L["Swing Timer"] = "스윙 타이머" -- Needs review
L["Talent Specialization"] = "특성 전문화" -- Needs review
-- L["Tank"] = ""
-- L["Tanking And Highest"] = ""
-- L["Tanking But Not Highest"] = ""
L["Target"] = "대상" -- Needs review
L["Thick Outline"] = "두꺼운 외곽선" -- Needs review
-- L["Third Tree"] = ""
-- L["Threat Situation"] = ""
L["Thrown"] = "던지기" -- Needs review
-- L["Timed"] = ""
L["Top"] = "위" -- Needs review
L["Top Left"] = "왼쪽 위" -- Needs review
L["Top Right"] = "오른쪽 위" -- Needs review
L["Top to Bottom"] = "위에서 아래로" -- Needs review
L["Total"] = "종합" -- Needs review
L["Totem"] = "토템" -- Needs review
L["Totem Name"] = "토템 이름" -- Needs review
L["Totem Type"] = "토템 종류" -- Needs review
L["Transmission error"] = "전송 오류" -- Needs review
L["Trigger:"] = "조건:" -- Needs review
L["Trigger Update"] = "조건 업데이트" -- Needs review
L["Undefined"] = "정의 안됨" -- Needs review
L["Unholy Rune #1"] = "부정 룬 #1" -- Needs review
L["Unholy Rune #2"] = "부정 룬 #2" -- Needs review
L["Unholy Runes"] = "부정 룬" -- Needs review
L["Unit"] = "유닛" -- Needs review
-- L["Unit Characteristics"] = ""
L["Unit Destroyed"] = "유닛 파괴됨" -- Needs review
L["Unit Died"] = "유닛 죽음" -- Needs review
L["Up"] = "위로" -- Needs review
-- L["Version error recevied higher"] = ""
L["Version error recevied lower"] = "이 디스플레이는 현재 WeakAuras 버전과 호환되지 않습니다 - %s 버전에서 제작되었으며, 현재 설치된 WeakAuras 버전은 %s 입니다. 이 디스플레이를 보내준 이에게 WeakAuras를 업데이트 하도록 알려주세요." -- Needs review
L["Warlock"] = "흑마법사" -- Needs review
L["Warrior"] = "전사" -- Needs review
L["Water"] = "물" -- Needs review
L["WeakAuras"] = "WeakAuras" -- Needs review
L["WeakAurasModelPaths"] = "WeakAuras - 3D 모델 경로" -- Needs review
-- L["WeakAurasModelPaths .toc Notes"] = ""
L["WeakAurasOptions"] = "WeakAuras - 옵션" -- Needs review
L["WeakAurasOptions .toc Notes"] = "WeakAuras의 GUI 옵션" -- Needs review
L["WeakAuras .toc Notes"] = "버프, 디버프, 혹은 여러가지 조건에 따라 그래픽과 정보를 보여주는 강력하고 종합적인 툴입니다" -- Needs review
L["WeakAurasTutorials"] = "WeakAuras - 설명서" -- Needs review
-- L["WeakAurasTutorials .toc Notes"] = ""
L["Weapon"] = "무기" -- Needs review
L["Weapon Enchant"] = "무기 강화" -- Needs review
L["Whisper"] = "귓속말" -- Needs review
L["Wobble"] = "흔들기" -- Needs review
L["Yell"] = "외치기" -- Needs review
L["Zone"] = "지역" -- Needs review
L["Options/1 Match"] = "1개 일치" -- Needs review
-- L["Options/Actions"] = ""
-- L["Options/Activate when the given aura(s) |cFFFF0000can't|r be found"] = ""
L["Options/Add a new display"] = "새 디스플레이 추가" -- Needs review
L["Options/Add Dynamic Text"] = "유동적 텍스트 추가" -- Needs review
L["Options/Addon"] = "애드온" -- Needs review
L["Options/Addons"] = "애드온" -- Needs review
-- L["Options/Add to group %s"] = ""
L["Options/Add to new Dynamic Group"] = "새 유동적 그룹에 추가" -- Needs review
L["Options/Add to new Group"] = "새 그룹 추가" -- Needs review
L["Options/Add Trigger"] = "조건 추가" -- Needs review
-- L["Options/A group that dynamically controls the positioning of its children"] = ""
L["Options/Align"] = "조정" -- Needs review
-- L["Options/Allow Full Rotation"] = ""
L["Options/Alpha"] = "투명도" -- Needs review
L["Options/Anchor"] = "기준점" -- Needs review
L["Options/Anchor Point"] = "기준점" -- Needs review
L["Options/Angle"] = "각도" -- Needs review
L["Options/Animate"] = "애니메이션" -- Needs review
L["Options/Animated Expand and Collapse"] = "확장 / 접기 애니메이션" -- Needs review
-- L["Options/Animation relative duration description"] = ""
L["Options/Animations"] = "애니메이션" -- Needs review
L["Options/Animation Sequence"] = "애니메이션 순서" -- Needs review
-- L["Options/Aquatic"] = ""
L["Options/Aura (Paladin)"] = "오라 (성기사" -- Needs review
L["Options/Aura(s)"] = "오라" -- Needs review
L["Options/Auto"] = "자동" -- Needs review
L["Options/Auto-cloning enabled"] = "자동 복제 활성화" -- Needs review
L["Options/Automatic Icon"] = "자동 아이콘" -- Needs review
L["Options/Backdrop Color"] = "배경 색상" -- Needs review
L["Options/Backdrop Style"] = "배경 스타일" -- Needs review
L["Options/Background"] = "배경" -- Needs review
L["Options/Background Color"] = "배경 색상" -- Needs review
-- L["Options/Background Inset"] = ""
-- L["Options/Background Offset"] = ""
L["Options/Background Texture"] = "배경 텍스쳐" -- Needs review
L["Options/Bar Alpha"] = "바 투명도" -- Needs review
L["Options/Bar Color"] = "바 색상" -- Needs review
L["Options/Bar Color Settings"] = "바 색상 설정" -- Needs review
L["Options/Bar in Front"] = "바에서 사용 할 폰트" -- Needs review
L["Options/Bar Texture"] = "바 텍스쳐" -- Needs review
-- L["Options/Battle"] = ""
L["Options/Bear"] = "곰" -- Needs review
-- L["Options/Berserker"] = ""
L["Options/Blend Mode"] = "혼합 모드" -- Needs review
-- L["Options/Blood"] = ""
L["Options/Border"] = "테두리" -- Needs review
L["Options/Border Color"] = "테두리 색상" -- Needs review
-- L["Options/Border Inset"] = ""
-- L["Options/Border Offset"] = ""
L["Options/Border Settings"] = "테두리 설정" -- Needs review
L["Options/Border Size"] = "테두리 크기" -- Needs review
L["Options/Border Style"] = "테두리 스타일" -- Needs review
L["Options/Bottom Text"] = "아래쪽 텍스트" -- Needs review
-- L["Options/Button Glow"] = ""
-- L["Options/Can be a name or a UID (e.g., party1). Only works on friendly players in your group."] = ""
L["Options/Cancel"] = "취소" -- Needs review
-- L["Options/Cat"] = ""
L["Options/Change the name of this display"] = "이 디스플레이의 이름 변경" -- Needs review
L["Options/Channel Number"] = "채널 번호" -- Needs review
L["Options/Check On..."] = "체크..." -- Needs review
L["Options/Choose"] = "선택" -- Needs review
L["Options/Choose Trigger"] = "조건 선택" -- Needs review
-- L["Options/Choose whether the displayed icon is automatic or defined manually"] = ""
-- L["Options/Clone option enabled dialog"] = ""
L["Options/Close"] = "닫기" -- Needs review
L["Options/Collapse"] = "접기" -- Needs review
L["Options/Collapse all loaded displays"] = "로딩된 모든 디스플레이 접기" -- Needs review
L["Options/Collapse all non-loaded displays"] = "로딩되지 않은 모든 디스플레이 접기" -- Needs review
L["Options/Color"] = "색상" -- Needs review
L["Options/Compress"] = "누르기" -- Needs review
-- L["Options/Concentration"] = ""
-- L["Options/Constant Factor"] = ""
L["Options/Control-click to select multiple displays"] = "Control-click - 여러 디스플레이 선택" -- Needs review
-- L["Options/Controls the positioning and configuration of multiple displays at the same time"] = ""
L["Options/Convert to..."] = "변환중..." -- Needs review
L["Options/Cooldown"] = "쿨다운" -- Needs review
L["Options/Copy"] = "복사" -- Needs review
L["Options/Copy settings from..."] = "설정 복사..." -- Needs review
L["Options/Copy settings from another display"] = "다른 디스플레이에서 설정 복사" -- Needs review
L["Options/Copy settings from %s"] = "%s에서 설정 복사" -- Needs review
-- L["Options/Count"] = ""
L["Options/Creating buttons: "] = "버튼 생성:" -- Needs review
L["Options/Creating options: "] = "옵션 생성:" -- Needs review
L["Options/Crop X"] = "X 자르기" -- Needs review
L["Options/Crop Y"] = "Y " -- Needs review
-- L["Options/Crusader"] = ""
L["Options/Custom Code"] = "개인추가 코드" -- Needs review
L["Options/Custom Trigger"] = "개인추가 조건" -- Needs review
-- L["Options/Custom trigger event tooltip"] = ""
-- L["Options/Custom trigger status tooltip"] = ""
-- L["Options/Custom Untrigger"] = ""
-- L["Options/Custom untrigger event tooltip"] = ""
L["Options/Death"] = "죽음" -- Needs review
-- L["Options/Death Rune"] = ""
L["Options/Debuff Type"] = "디버프 유형" -- Needs review
L["Options/Defensive"] = "방어" -- Needs review
L["Options/Delete"] = "삭제" -- Needs review
L["Options/Delete all"] = "모두 삭제" -- Needs review
-- L["Options/Delete children and group"] = ""
L["Options/Deletes this display - |cFF8080FFShift|r must be held down while clicking"] = "이 디스플레이 삭제 - |cFF8080FFShift|r키를 누르고 클릭해야 합니다" -- Needs review
L["Options/Delete Trigger"] = "조건 삭제" -- Needs review
L["Options/Desaturate"] = "흑백" -- Needs review
-- L["Options/Devotion"] = ""
L["Options/Disabled"] = "비활성화됨" -- Needs review
-- L["Options/Discrete Rotation"] = ""
L["Options/Display"] = "디스플레이" -- Needs review
L["Options/Display Icon"] = "디스플레이 아이콘" -- Needs review
L["Options/Display Text"] = "디스플레이 텍스트" -- Needs review
-- L["Options/Distribute Horizontally"] = ""
-- L["Options/Distribute Vertically"] = ""
L["Options/Do not copy any settings"] = "설정을 복사하지 않음" -- Needs review
-- L["Options/Do not group this display"] = ""
L["Options/Duplicate"] = "복제" -- Needs review
L["Options/Duration Info"] = "지속시간 정보" -- Needs review
L["Options/Duration (s)"] = "지속시간 (s)" -- Needs review
L["Options/Dynamic Group"] = "유동적 그룹" -- Needs review
-- L["Options/Dynamic text tooltip"] = ""
L["Options/Enabled"] = "활성화됨" -- Needs review
L["Options/Enter an aura name, partial aura name, or spell id"] = "오라 이름 / 오라의 부분 이름 / 주문ID를 입력하세요," -- Needs review
L["Options/Event Type"] = "이벤트 유형" -- Needs review
L["Options/Expand"] = "확장" -- Needs review
L["Options/Expand all loaded displays"] = "로딩된 모든 디스플레이 확장" -- Needs review
L["Options/Expand all non-loaded displays"] = "로딩되지 않은 모드 디스플레이 확장" -- Needs review
L["Options/Expand Text Editor"] = "텍스트 편집창 확장" -- Needs review
L["Options/Expansion is disabled because this group has no children"] = "이 그룹은 자식이 없기 떄문에 확장이 비활성화되었습니다" -- Needs review
L["Options/Export"] = "내보내기" -- Needs review
L["Options/Export to Lua table..."] = "Lua table로 내보내기" -- Needs review
L["Options/Export to string..."] = "문자열로 내보내기" -- Needs review
-- L["Options/Fade"] = ""
L["Options/Finish"] = "완료" -- Needs review
L["Options/Fire Resistance"] = "화염 저항" -- Needs review
-- L["Options/Flight(Non-Feral)"] = ""
L["Options/Font"] = "폰트" -- Needs review
L["Options/Font Flags"] = "폰트 효과" -- Needs review
L["Options/Font Size"] = "폰트 크기" -- Needs review
L["Options/Font Type"] = "폰트 종류" -- Needs review
L["Options/Foreground Color"] = "앞면 색상" -- Needs review
L["Options/Foreground Texture"] = "앞면 텍스쳐" -- Needs review
L["Options/Form (Druid)"] = "폼 (드루이드)" -- Needs review
L["Options/Form (Priest)"] = "형상 (사제)" -- Needs review
L["Options/Form (Shaman)"] = "폼 (주술사)" -- Needs review
L["Options/Form (Warlock)"] = "폼 (흑마법사)" -- Needs review
L["Options/Frame"] = "프레임" -- Needs review
L["Options/Frame Strata"] = "프레임 표시순위" -- Needs review
L["Options/Frost"] = "냉기" -- Needs review
L["Options/Frost Resistance"] = "냉기 저항" -- Needs review
L["Options/Full Scan"] = "모두 스캔" -- Needs review
-- L["Options/Ghost Wolf"] = ""
-- L["Options/Glow Action"] = ""
-- L["Options/Group aura count description"] = ""
L["Options/Group Member Count"] = "그룹 멤버 수" -- Needs review
-- L["Options/Group (verb)"] = ""
L["Options/Height"] = "높이" -- Needs review
-- L["Options/Hide this group's children"] = ""
L["Options/Hide When Not In Group"] = "파티중이 아닐 때 숨기기" -- Needs review
-- L["Options/Horizontal Align"] = ""
L["Options/Icon Info"] = "아이콘 정보" -- Needs review
L["Options/Ignored"] = "무시됨" -- Needs review
L["Options/Ignore GCD"] = "글로벌CD 무시" -- Needs review
L["Options/%i Matches"] = "%i 일치" -- Needs review
L["Options/Import"] = "가져오기" -- Needs review
L["Options/Import a display from an encoded string"] = "암호화된 문자열에서 디스플레이 가져오기" -- Needs review
L["Options/Justify"] = "정렬" -- Needs review
L["Options/Left Text"] = "왼쪽 텍스트" -- Needs review
L["Options/Load"] = "불러오기" -- Needs review
L["Options/Loaded"] = "로딩됨" -- Needs review
-- L["Options/Main"] = ""
L["Options/Main Trigger"] = "메인 조건" -- Needs review
L["Options/Mana (%)"] = "마나 (%)" -- Needs review
L["Options/Manage displays defined by Addons"] = "애드온에서 디스플레이 정의를 관리합니다" -- Needs review
L["Options/Message Prefix"] = "메세지 말머리" -- Needs review
L["Options/Message Suffix"] = "메세지 말꼬리" -- Needs review
-- L["Options/Metamorphosis"] = ""
L["Options/Mirror"] = "거울효과" -- Needs review
L["Options/Model"] = "모델" -- Needs review
-- L["Options/Moonkin/Tree/Flight(Feral)"] = ""
L["Options/Move Down"] = "아래로 이동" -- Needs review
-- L["Options/Move this display down in its group's order"] = ""
-- L["Options/Move this display up in its group's order"] = ""
L["Options/Move Up"] = "위로 이동" -- Needs review
L["Options/Multiple Displays"] = "다중 디스플레이" -- Needs review
L["Options/Multiple Triggers"] = "다중 조건" -- Needs review
-- L["Options/Multiselect ignored tooltip"] = ""
-- L["Options/Multiselect multiple tooltip"] = ""
-- L["Options/Multiselect single tooltip"] = ""
-- L["Options/Must be spelled correctly!"] = ""
L["Options/Name Info"] = "이름 정보" -- Needs review
-- L["Options/Negator"] = ""
L["Options/New"] = "새로운" -- Needs review
L["Options/Next"] = "다음" -- Needs review
-- L["Options/No"] = ""
L["Options/No Children"] = "자식 없음" -- Needs review
-- L["Options/Not all children have the same value for this option"] = ""
L["Options/Not Loaded"] = "로딩되지 않음" -- Needs review
L["Options/No tooltip text"] = "툴팁 텍스트 없음" -- Needs review
L["Options/% of Progress"] = "% 진행" -- Needs review
L["Options/Okay"] = "확인" -- Needs review
L["Options/On Hide"] = "숨겨짐" -- Needs review
-- L["Options/Only match auras cast by people other than the player"] = ""
L["Options/Only match auras cast by the player"] = "플레이어가 시전한 오라와 일치할때만" -- Needs review
L["Options/On Show"] = "보여짐" -- Needs review
L["Options/Operator"] = "연산자" -- Needs review
L["Options/or"] = "혹은" -- Needs review
L["Options/Orientation"] = "방향" -- Needs review
-- L["Options/Other"] = ""
L["Options/Outline"] = "외곽선" -- Needs review
-- L["Options/Own Only"] = ""
L["Options/Player Character"] = "플레이어 캐릭터" -- Needs review
L["Options/Play Sound"] = "소리 재생" -- Needs review
-- L["Options/Presence (DK)"] = ""
-- L["Options/Presence (Rogue)"] = ""
-- L["Options/Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = ""
-- L["Options/Primary"] = ""
L["Options/Progress Bar"] = "진행 바" -- Needs review
L["Options/Progress Texture"] = "진행 텍스쳐" -- Needs review
-- L["Options/Put this display in a group"] = ""
L["Options/Ready For Use"] = "사용 가능" -- Needs review
L["Options/Re-center X"] = "내부 X 좌표" -- Needs review
L["Options/Re-center Y"] = "내부 Y 좌표" -- Needs review
-- L["Options/Remaining Time Precision"] = ""
L["Options/Remove this display from its group"] = "그룹에서 이 디스플레이 삭제" -- Needs review
L["Options/Rename"] = "이름 변경" -- Needs review
-- L["Options/Requesting display information"] = ""
L["Options/Required For Activation"] = "활성화 필요" -- Needs review
-- L["Options/Retribution"] = ""
L["Options/Right-click for more options"] = "RightClick - 추가 옵션" -- Needs review
L["Options/Right Text"] = "오른쪽 텍스트" -- Needs review
L["Options/Rotate"] = "회전" -- Needs review
-- L["Options/Rotate In"] = ""
-- L["Options/Rotate Out"] = ""
L["Options/Rotate Text"] = "텍스트 회전" -- Needs review
L["Options/Rotation"] = "회전" -- Needs review
-- L["Options/Same"] = ""
L["Options/Search"] = "검색" -- Needs review
-- L["Options/Secondary"] = ""
L["Options/Send To"] = "보내기..." -- Needs review
L["Options/Set tooltip description"] = "툴팁 설명 설정" -- Needs review
-- L["Options/Shadow Dance"] = ""
-- L["Options/Shadowform"] = ""
L["Options/Shadow Resistance"] = "암흑 저항" -- Needs review
L["Options/Shift-click to create chat link"] = "Shift-click - |cFF8800FF[채팅 링크] 생성" -- Needs review
-- L["Options/Show all matches (Auto-clone)"] = ""
-- L["Options/Show players that are |cFFFF0000not affected"] = ""
L["Options/Shows a 3D model from the game files"] = "게임 데이터의 3D 모델 보이기" -- Needs review
L["Options/Shows a custom texture"] = "개인추가 텍스쳐 보이기" -- Needs review
L["Options/Shows a progress bar with name, timer, and icon"] = "이름 / 타이머 / 아이콘의 진행 바 보이기" -- Needs review
-- L["Options/Shows a spell icon with an optional a cooldown overlay"] = ""
L["Options/Shows a texture that changes based on duration"] = "지속시간을 텍스쳐로 나타냅니다" -- Needs review
-- L["Options/Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = ""
-- L["Options/Shows the remaining or expended time for an aura or timed event"] = ""
L["Options/Show this group's children"] = "이 그룹의 자식 보이기" -- Needs review
L["Options/Size"] = "크기" -- Needs review
-- L["Options/Slide"] = ""
-- L["Options/Slide In"] = ""
-- L["Options/Slide Out"] = ""
L["Options/Sort"] = "정렬" -- Needs review
L["Options/Sound"] = "사운드" -- Needs review
L["Options/Sound Channel"] = "사운드 채널" -- Needs review
L["Options/Sound File Path"] = "사운드 파일 경로" -- Needs review
L["Options/Space"] = "공간" -- Needs review
L["Options/Space Horizontally"] = "수평 공간" -- Needs review
L["Options/Space Vertically"] = "수직 공간" -- Needs review
L["Options/Spell ID"] = "주문 ID" -- Needs review
-- L["Options/Spell ID dialog"] = ""
L["Options/Stack Count"] = "묶음 카운트" -- Needs review
L["Options/Stack Count Position"] = "중첩 횟수 위치" -- Needs review
L["Options/Stack Info"] = "중첩 정보" -- Needs review
L["Options/Stacks Settings"] = "묶음 설정" -- Needs review
-- L["Options/Stagger"] = ""
L["Options/Stance (Warrior)"] = "태세 (전사)" -- Needs review
L["Options/Start"] = "시작" -- Needs review
L["Options/Stealable"] = "훔치기 가능" -- Needs review
-- L["Options/Stealthed"] = ""
-- L["Options/Sticky Duration"] = ""
L["Options/Temporary Group"] = "임시 그룹" -- Needs review
L["Options/Text"] = "텍스트" -- Needs review
L["Options/Text Color"] = "텍스트 색상" -- Needs review
L["Options/Text Position"] = "텍스트 위치" -- Needs review
L["Options/Text Settings"] = "텍스트 설정" -- Needs review
L["Options/Texture"] = "텍스쳐" -- Needs review
-- L["Options/The children of this group have different display types, so their display options cannot be set as a group."] = ""
-- L["Options/The duration of the animation in seconds."] = ""
L["Options/The type of trigger"] = "조건의 유형" -- Needs review
-- L["Options/This condition will not be tested"] = ""
L["Options/This display is currently loaded"] = "이 디스플레이 현재 로딩됨" -- Needs review
L["Options/This display is not currently loaded"] = "이 디스플레이 현재 로딩되지 않음" -- Needs review
L["Options/This display will only show when |cFF00FF00%s"] = "|cFF00FF00%s 일때만 이 디스플레이 보임" -- Needs review
L["Options/This display will only show when |cFFFF0000 Not %s"] = "|cFFFF0000 Not %s 이지 않을때만 이 디스플레이 보임" -- Needs review
-- L["Options/This region of type \"%s\" has no configuration options."] = ""
-- L["Options/Time in"] = ""
L["Options/Timer"] = "타이머" -- Needs review
L["Options/Timer Settings"] = "타이머 설정" -- Needs review
L["Options/Toggle the visibility of all loaded displays"] = "로딩된 모든 디스플레이 보이기 토글" -- Needs review
L["Options/Toggle the visibility of all non-loaded displays"] = "로딩되지 않은 모든 디스플레이 보이기 토글" -- Needs review
L["Options/Toggle the visibility of this display"] = "이 디스플레이 보이기 토글" -- Needs review
L["Options/to group's"] = "그룹 기준" -- Needs review
L["Options/Tooltip"] = "툴팁" -- Needs review
L["Options/Tooltip on Mouseover"] = "마우스오버 툴팁" -- Needs review
L["Options/Top Text"] = "윗부분 텍스트" -- Needs review
L["Options/to screen's"] = "화면 기준" -- Needs review
-- L["Options/Total Time Precision"] = ""
-- L["Options/Tracking"] = ""
-- L["Options/Travel"] = ""
L["Options/Trigger"] = "조건" -- Needs review
L["Options/Trigger %d"] = "조건 %d" -- Needs review
L["Options/Triggers"] = "조건" -- Needs review
L["Options/Type"] = "유형" -- Needs review
-- L["Options/Ungroup"] = ""
L["Options/Unholy"] = "부정" -- Needs review
-- L["Options/Unit Exists"] = ""
-- L["Options/Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = ""
L["Options/Unstealthed"] = "은신풀림" -- Needs review
-- L["Options/Update Custom Text On..."] = ""
L["Options/Use Full Scan (High CPU)"] = "전체 스캔 사용 (높은 CPU 사용률)" -- Needs review
-- L["Options/Use tooltip \"size\" instead of stacks"] = ""
L["Options/Vertical Align"] = "수직 조정" -- Needs review
-- L["Options/View"] = ""
L["Options/Width"] = "가로" -- Needs review
L["Options/X Offset"] = "X 좌표" -- Needs review
L["Options/X Scale"] = "가로 크기" -- Needs review
L["Options/Yes"] = "예" -- Needs review
L["Options/Y Offset"] = "Y 좌표" -- Needs review
L["Options/Y Scale"] = "세로 크기" -- Needs review
L["Options/Z Offset"] = "Z 좌표" -- Needs review
L["Options/Zoom"] = "줌" -- Needs review
L["Options/Zoom In"] = "줌 인" -- Needs review
L["Options/Zoom Out"] = "줌 아웃" -- Needs review
L["Tutorials/Actions and Animations: 1/7"] = "액션 & 애니메이션: 1/7" -- Needs review
L["Tutorials/Actions and Animations: 2/7"] = "액션 & 애니메이션: 2/7" -- Needs review
L["Tutorials/Actions and Animations: 3/7"] = "액션 & 애니메이션: 3/7" -- Needs review
L["Tutorials/Actions and Animations: 4/7"] = "액션 & 애니메이션: 4/7" -- Needs review
L["Tutorials/Actions and Animations: 5/7"] = "액션 & 애니메이션: 5/7" -- Needs review
L["Tutorials/Actions and Animations: 6/7"] = "액션 & 애니메이션: 6/7" -- Needs review
L["Tutorials/Actions and Animations: 7/7"] = "액션 & 애니메이션: 7/7" -- Needs review
L["Tutorials/Actions and Animations Text"] = [=[To test your animation, you'll have to hide your display and make it appear again. This can be done using the display's View button on the sidebar.

Click it a few times to see your Start animation.]=] -- Needs review
L["Tutorials/Activation Settings: 1/5"] = "활성화 설정: 1/5" -- Needs review
L["Tutorials/Activation Settings: 2/5"] = "활성화 설정: 2/5" -- Needs review
L["Tutorials/Activation Settings: 3/5"] = "활성화 설정: 3/5" -- Needs review
L["Tutorials/Activation Settings: 4/5"] = "활성화 설정: 4/5" -- Needs review
L["Tutorials/Activation Settings: 5/5"] = "활성화 설정: 5/5" -- Needs review
L["Tutorials/Activation Settings Text"] = "활성화 설정 텍스트" -- Needs review
-- L["Tutorials/Auto-cloning: 1/10"] = ""
-- L["Tutorials/Auto-cloning 1/10 Text"] = ""
-- L["Tutorials/Beginners Finished Text"] = ""
L["Tutorials/Beginners Guide Desc"] = "초보자 가이드" -- Needs review
L["Tutorials/Beginners Guide Desc Text"] = "WeakAuras 기본적인 옵션 설정에 대하여 안내합니다" -- Needs review
L["Tutorials/Create a Display: 1/5"] = "디스플레이 생성: 1/5" -- Needs review
L["Tutorials/Create a Display: 2/5"] = "디스플레이 생성: 2/5" -- Needs review
L["Tutorials/Create a Display: 3/5"] = "디스플레이 생성: 3/5" -- Needs review
L["Tutorials/Create a Display: 4/5"] = "디스플레이 생성: 4/5" -- Needs review
L["Tutorials/Create a Display: 5/5"] = "디스플레이 생성: 5/5" -- Needs review
-- L["Tutorials/Create a Display Text"] = ""
L["Tutorials/Display Options: 1/4"] = "디스플레이 옵션: 1/4" -- Needs review
-- L["Tutorials/Display Options 1/4 Text"] = ""
L["Tutorials/Display Options: 2/4"] = "디스플레이 옵션: 2/4" -- Needs review
-- L["Tutorials/Display Options 2/4 Text"] = ""
L["Tutorials/Display Options: 4/4"] = "디스플레이 옵션: 4/4" -- Needs review
-- L["Tutorials/Display Options 4/4 Text"] = ""
L["Tutorials/Dynamic Group Options: 2/4"] = "유동적 그룹 옵션: 2/4" -- Needs review
-- L["Tutorials/Dynamic Group Options 2/4 Text"] = ""
L["Tutorials/Dynamic Group Options: 3/4"] = "유동적 그룹 옵션: 3/4" -- Needs review
-- L["Tutorials/Dynamic Group Options 3/4 Text"] = ""
L["Tutorials/Dynamic Group Options: 4/4"] = "유동적 그룹 옵션: 4/4" -- Needs review
-- L["Tutorials/Dynamic Group Options 4/4 Text"] = ""
L["Tutorials/Finished"] = "마침" -- Needs review
L["Tutorials/Full-scan Auras: 2/10"] = "오라 전체 스캔: 2/10" -- Needs review
L["Tutorials/Full-scan Auras 2/10 Text"] = "첫번째, 모두 스캔 옵션을 활성화" -- Needs review
L["Tutorials/Full-scan Auras: 3/10"] = "오라 전체 스캔: 3/10" -- Needs review
-- L["Tutorials/Full-scan Auras 3/10 Text"] = ""
L["Tutorials/Full-scan Auras: 4/10"] = "오라 전체 스캔: 4/10" -- Needs review
-- L["Tutorials/Full-scan Auras 4/10 Text"] = ""
L["Tutorials/Full-scan Auras: 5/10"] = "오라 전체 스캔: 5/10" -- Needs review
-- L["Tutorials/Full-scan Auras 5/10 Text"] = ""
L["Tutorials/Group Auras 6/10"] = "그룹 오라: 6/10" -- Needs review
-- L["Tutorials/Group Auras 6/10 Text"] = ""
L["Tutorials/Group Auras: 7/10"] = "그룹 오라: 7/10" -- Needs review
-- L["Tutorials/Group Auras 7/10 Text"] = ""
L["Tutorials/Group Auras: 8/10"] = "그룹 오라: 8/10" -- Needs review
-- L["Tutorials/Group Auras 8/10 Text"] = ""
L["Tutorials/Home"] = "처음으로" -- Needs review
L["Tutorials/Multi-target Auras: 10/10"] = "다중 대상 오라: 10/10" -- Needs review
-- L["Tutorials/Multi-target Auras 10/10 Text"] = ""
L["Tutorials/Multi-target Auras: 9/10"] = "다중 대상 오라: 9/10" -- Needs review
-- L["Tutorials/Multi-target Auras 9/10 Text"] = ""
L["Tutorials/New in 1.4:"] = "1.4의 새 기능:" -- Needs review
L["Tutorials/New in 1.4 Desc:"] = "1.4의 새 기능" -- Needs review
L["Tutorials/New in 1.4 Desc Text"] = "WeakAuras 1.4의 새로운 기능을 봅니다" -- Needs review
-- L["Tutorials/New in 1.4 Finnished Text"] = ""
-- L["Tutorials/New in 1.4 Text1"] = ""
-- L["Tutorials/New in 1.4 Text2"] = ""
L["Tutorials/Previous"] = "이전" -- Needs review
L["Tutorials/Trigger Options: 1/4"] = "조건 옵션: 1/4" -- Needs review
-- L["Tutorials/Trigger Options 1/4 Text"] = ""
L["Tutorials/Trigger Options: 2/4"] = "조건 옵션: 2/4" -- Needs review
-- L["Tutorials/Trigger Options 2/4 Text"] = ""
L["Tutorials/Trigger Options: 3/4"] = "조건 옵션: 3/4" -- Needs review
-- L["Tutorials/Trigger Options 3/4 Text"] = ""
L["Tutorials/Trigger Options: 4/4"] = "조건 옵션: 4/4" -- Needs review
-- L["Tutorials/Trigger Options 4/4 Text"] = ""
L["Tutorials/WeakAuras Tutorials"] = "WeakAuras 설명서" -- Needs review
L["Tutorials/Welcome"] = "환영합니다" -- Needs review
L["Tutorials/Welcome Text"] = [=[|cFF8800FFWeakAuras|r 초보자 가이드에 오신 것을 환영합니다.

이 가이드는 WeakAuras를 어떻게 사용하는지 보여주며. 
옵션을 설정하는 기본적인 방법에 대해 알려줍니다.]=] -- Needs review



