
local L = LibStub('AceLocale-3.0'):NewLocale('RazerNaga-Config', 'ruRU')
if not L then return end

L.Scale = 'Масштаб'
L.Opacity = 'Непрозрачность'
L.FadedOpacity = 'Затухание непрозрачности'
L.Visibility = 'Видимость'
L.Spacing = 'Интервал'
L.Padding = 'Заполнение'
L.Layout = 'Раскладка'
L.Columns = 'Колонки'
L.Size = 'Размер'
L.Modifiers = 'Модификаторы'
L.QuickPaging = 'Быстрое пролистывание'
L.State_HELP= 'Справка'
L.State_HARM = 'Урон'
L.Targeting = 'Прицеливание'
L.ShowStates = 'Показывает состояния'
L.Set = 'Установить'
L.Save = 'Сохранить'
L.Copy = 'Копировать'
L.Delete = 'Клавиша Delete'
L.Bar = 'Панель %d'
L.RightClickUnit = 'Щелчок правой кнопкой для выбора цели'
L.RCUPlayer = 'Себя'
L.RCUFocus = 'Фокус'
L.RCUToT = 'Цель цели'
L.EnterName = 'Введите имя'
L.PossessBar = 'Панель владения'
L.Profiles = 'Профили'
L.ProfilesPanelDesc = 'Позволяют управлять сохраненными раскладками RazerNaga'
L.ShowMacroText = 'Показать текст макроса'
L.ShowBindingText = 'Показать текст привязки'
L.ShowEmptyButtons = 'Показать неназначенные кнопки'
L.LockActionButtons = 'Блокировать позиции кнопок действия'
L.EnterBindingMode = 'Назначить клавиши…'
L.EnterConfigMode = 'Настроить панели…'
L.ActionBarSettings = 'Параметры панели действий %d'
L.BarSettings = '%s параметры панели'
L.ShowTooltips = 'Показать всплывающие подсказки'
L.OneBag = 'Только сумка'
L.ShowKeyring = 'Показать брелок'
L.StickyBars = 'Прикрепляющиеся панели'
L.ShowMinimapButton = 'Показать кнопку миникарты'
L.DisableMenuButtons = 'Отключение кнопок'
L.EnableAutoBindings = 'Всегда использовать кнопки Razer Naga'
L.Bindings = 'Привязки'
L.BindingSetModifier = 'Модифицирующая клавиша'

L.Advanced = 'Дополнительные настройки'
L.LeftToRight = 'Расположение кнопок слева направо'
L.TopToBottom = 'Расположение кнопок сверху вниз'
L.LinkedOpacity = 'Закрепленная панель наследует непрозрачность'
L.ClickThrough = 'Включить нечувствительность к клику мышкой'

--totems
L.ShowTotems = 'Показать тотемы'
L.ShowTotemRecall = 'Показать вызов'

--modifier highlighting
L.HighlightModifiers = 'Выделить панели модификатора'

L.ShowTooltipsCombat = 'Показывать подсказки в сражениях'