
local L = LibStub('AceLocale-3.0'):NewLocale('RazerNaga-Config', 'zhCN')
if not L then return end

L.Scale = '大小'
L.Opacity = '不透明度'
L.FadedOpacity = '淡出参数'
L.Visibility = '可见性'
L.Spacing = '间距'
L.Padding = '填充'
L.Layout = '布局'
L.Columns = '列'
L.Size = '尺寸'
L.Modifiers = '修改者'
L.QuickPaging = '快速变换'
L.State_HELP= '帮助'
L.State_HARM = '伤害'
L.Targeting = '目标'
L.ShowStates = '显示状态'
L.Set = '设置'
L.Save = '保存'
L.Copy = '复制'
L.Delete = '删除'
L.Bar = '栏 %d'
L.RightClickUnit = '右键单击目标'
L.RCUPlayer = '自我'
L.RCUFocus = '专注'
L.RCUToT = '目标的目标'
L.EnterName = '输入名称'
L.PossessBar = '进度条'
L.Profiles = '配置文件'
L.ProfilesPanelDesc = '允许您管理保存的那伽梵蛇游戏鼠标布局'
L.ShowMacroText = '显示宏文本'
L.ShowBindingText = '显示绑定文本'
L.ShowEmptyButtons = '显示空按钮'
L.LockActionButtons = '锁定动作按钮位置'
L.EnterBindingMode = '绑定键...'
L.EnterConfigMode = '配置栏...'
L.ActionBarSettings = '动作栏 %d 设置'
L.BarSettings = '%s 栏设置'
L.ShowTooltips = '显示工具提示'
L.OneBag = '背包整合'
L.ShowKeyring = '显示密钥环'
L.StickyBars = '动作栏吸附'
L.ShowMinimapButton = '显示小地图按钮'
L.DisableMenuButtons = '禁用按键'
L.EnableAutoBindings = '始终使用那伽梵蛇游戏鼠标按钮'
L.Bindings = '绑定'
L.BindingSetModifier = '修改者键'

L.Advanced = '高级'
L.LeftToRight = '从左到右的按钮键布局'
L.TopToBottom = '从顶部到底部的按钮键布局'
L.LinkedOpacity = '与被吸附动作条透明度保持一致'
L.ClickThrough = '启用穿越点击'

--totems
L.ShowTotems = '显示标识'
L.ShowTotemRecall = '显示恢复'

--modifier highlighting
L.HighlightModifiers = '突出显示修改者栏'

L.ShowTooltipsCombat = '战斗中显示工具提示'