
local L = LibStub('AceLocale-3.0'):NewLocale('RazerNaga-Config', 'deDE')
if not L then return end

L.Scale = 'Wert'
L.Opacity = 'Opazität'
L.FadedOpacity = 'Verblasste Transparenz'
L.Visibility = 'Sichtbarkeit'
L.Spacing = 'Abstand'
L.Padding = 'Füllung'
L.Layout = 'Layout'
L.Columns = 'Spalten'
L.Size = 'Größe'
L.Modifiers = 'Wandler'
L.QuickPaging = 'Schneller Kombinationswechsel'
L.State_HELP= 'Hilfe'
L.State_HARM = 'Schaden'
L.Targeting = 'Zielend'
L.ShowStates = 'Status anzeigen'
L.Set = 'Festlegen'
L.Save = 'Speichern'
L.Copy = 'Kopieren'
L.Delete = 'Löschen'
L.Bar = 'Leiste %d'
L.RightClickUnit = 'Rechtsklick Ziel'
L.RCUPlayer = 'Selbst'
L.RCUFocus = 'Fokus'
L.RCUToT = 'Ziel des Ziels'
L.EnterName = 'Name eingeben'
L.PossessBar = 'Besitz-Leiste'
L.Profiles = 'Profile'
L.ProfilesPanelDesc = 'Ermöglicht es, gespeicherte RazerNaga Layouts zu verwalten.'
L.ShowMacroText = 'Makrotext anzeigen'
L.ShowBindingText = 'Zuweisungstext anzeigen'
L.ShowEmptyButtons = 'Leere Tasten anzeigen'
L.LockActionButtons = 'Positionen der Aktionstasten festlegen '
L.EnterBindingMode = 'Tasten zuweisen…'
L.EnterConfigMode = 'Leisten konfigurieren…'
L.ActionBarSettings = 'Einstellungen der Aktionsleiste %d'
L.BarSettings = '%s Leisten-Einstellungen '
L.ShowTooltips = 'Tooltipps anzeigen'
L.OneBag = 'Eine Tasche'
L.ShowKeyring = 'Schlüsselring anzeigen'
L.StickyBars = 'Leisten verbinden'
L.ShowMinimapButton = 'Taste der Minikarte anzeigen'
L.DisableMenuButtons = 'Tasten deaktivieren'
L.EnableAutoBindings = 'Immer Razer Naga Tasten verwenden'
L.Bindings = 'Zuweisungen'
L.BindingSetModifier = 'Modifikationstaste'

L.Advanced = 'Erweitert'
L.LeftToRight = 'Layout-Tasten von links nach rechts'
L.TopToBottom = 'Layout-Tasten von oben nach unten'
L.LinkedOpacity = 'Angedockte Leisten übernehmen Transparenz'
L.ClickThrough = 'Durchklicken aktivieren'

--totems
L.ShowTotems = 'Totems anzeigen'
L.ShowTotemRecall = 'Recall anzeigen'

--modifier highlighting
L.HighlightModifiers = 'Modifierleisten hervorheben (Modifier: Shift, Strg, Alt, etc.)'

L.ShowTooltipsCombat = 'Zeige Kurzinfos w√§hrend des Kampfes'