
local L = LibStub('AceLocale-3.0'):NewLocale('RazerNaga-Config', 'koKR')
if not L then return end

L.Scale = '배율'
L.Opacity = '불투명도'
L.FadedOpacity = '빛바랜 불투명도'
L.Visibility = '가시도'
L.Spacing = '간격'
L.Padding = '안쪽 여백'
L.Layout = '레이아웃'
L.Columns = '열'
L.Size = '크기'
L.Modifiers = '보조'
L.QuickPaging = '빠른 호출'
L.State_HELP= '우호'
L.State_HARM = '적대'
L.Targeting = '목표 겨냥'
L.ShowStates = '상태 표시'
L.Set = '설정'
L.Save = '저장'
L.Copy = '복사'
L.Delete = '삭제'
L.Bar = '바 %d'
L.RightClickUnit = '목표 오른쪽 클릭'
L.RCUPlayer = '셀프'
L.RCUFocus = '초점'
L.RCUToT = '목표의 목표'
L.EnterName = '이름 입력'
L.PossessBar = '지배바'
L.Profiles = '프로파일'
L.ProfilesPanelDesc = '저장된 RazerNaga 레이아웃을 관리할 수 있도록 허용'
L.ShowMacroText = '매크로 텍스트 표시'
L.ShowBindingText = '바인딩 텍스트 표시'
L.ShowEmptyButtons = '빈 버튼 표시'
L.LockActionButtons = '액션 버튼 위치 잠그기'
L.EnterBindingMode = '키 바인딩...'
L.EnterConfigMode = '바 구성...'
L.ActionBarSettings = '액션바 %d 설정'
L.BarSettings = '%s 바 설정'
L.ShowTooltips = '툴팁 표시'
L.OneBag = '원 백'
L.ShowKeyring = '키링 표시'
L.StickyBars = '스틱키 바'
L.ShowMinimapButton = '미니맵 버튼 표시'
L.DisableMenuButtons = '버튼 비활성화'
L.EnableAutoBindings = '언제나 Razer Naga 버튼 사용'
L.Bindings = '바인딩'
L.BindingSetModifier = '보조키'

L.Advanced = '고급'
L.LeftToRight = '왼쪽에서 오른쪽 레이아웃 버튼'
L.TopToBottom = '위쪽에서 아래쪽 레이아웃 버튼'
L.LinkedOpacity = '도킹된 바 불투명도를 상속'
L.ClickThrough = '마우스 통과 활성화'


--totems
L.ShowTotems = '토템 표시'
L.ShowTotemRecall = '리콜 표시'

--modifier highlighting
L.HighlightModifiers = '보조키 바 강조'

L.ShowTooltipsCombat = '전투중 툴팁 표시'