
local L = LibStub('AceLocale-3.0'):NewLocale('RazerNaga-Config', 'esMX')
if not L then return end

L.Scale = 'Escala'
L.Opacity = 'Opacidad'
L.FadedOpacity = 'Opacidad desvanecida'
L.Visibility = 'Visibilidad'
L.Spacing = 'Espaciado'
L.Padding = 'Padding'
L.Layout = 'Diseño'
L.Columns = 'Columnas'
L.Size = 'Tamaño'
L.Modifiers = 'Modificadores'
L.QuickPaging = 'Accesos rápidos'
L.State_HELP= 'Ayuda'
L.State_HARM = 'Dañar'
L.Targeting = 'Orientación'
L.ShowStates = 'Mostrar estados'
L.Set = 'Ajustar'
L.Save = 'Guardar'
L.Copy = 'Copiar'
L.Delete = 'Eliminar'
L.Bar = 'Barra %d'
L.RightClickUnit = 'Haga clic derecho en el blanco'
L.RCUPlayer = 'Propio'
L.RCUFocus = 'Enfocar'
L.RCUToT = 'Blanco del blanco'
L.EnterName = 'Ingresar nombre'
L.PossessBar = 'Barra de posesiones'
L.Profiles = 'Perfiles'
L.ProfilesPanelDesc = 'Te permite administrar los diseños de Razer Naga guardados'
L.ShowMacroText = 'Mostrar texto de macro'
L.ShowBindingText = 'Mostrar texto de unión'
L.ShowEmptyButtons = 'Mostrar botones sin habilidades o hechizos'
L.LockActionButtons = 'Bloquear posiciones del botón de acción'
L.EnterBindingMode = 'Unir teclas…'
L.EnterConfigMode = 'Configurar barras…'
L.ActionBarSettings = 'Configuración de la barra de acción %d'
L.BarSettings = '%s Configuración de la barra'
L.ShowTooltips = 'Mostrar información sobre herramientas'
L.OneBag = 'Una mochila'
L.ShowKeyring = 'Mostrar anillo de teclas'
L.StickyBars = 'Barras combinadas'
L.ShowMinimapButton = 'Mostrar botón de mapa en miniatura'
L.DisableMenuButtons = 'Deshabilitar botones'
L.EnableAutoBindings = 'Utilizar siempre los botones de Razer Naga'
L.Bindings = 'Uniones'
L.BindingSetModifier = 'Tecla Modificador'

L.Advanced = 'Avanzado'
L.LeftToRight = 'Distribución de botones de izquierda a derecha'
L.TopToBottom = 'Distribución de botones de arriba a abajo'
L.LinkedOpacity = 'Barras acopladas con opacidad heredada'
L.ClickThrough = 'Activar seguimiento de clics'

--totems
L.ShowTotems = 'Mostrar emblemas'
L.ShowTotemRecall = 'Mostrar recordatorios'

--modifier highlighting
L.HighlightModifiers = 'Resaltar barras modificadoras'

L.ShowTooltipsCombat = 'Mostrar descripción emergente en combate'