
local L = LibStub('AceLocale-3.0'):NewLocale('RazerNaga-Config', 'zhTW')
if not L then return end

L.Scale = '大小'
L.Opacity = '不透明度'
L.FadedOpacity = '淡化不透明度'
L.Visibility = '可見度'
L.Spacing = '間距'
L.Padding = '邊框間距'
L.Layout = '配置'
L.Columns = '欄'
L.Size = '尺寸'
L.Modifiers = '輔助'
L.QuickPaging = '快速尋呼'
L.State_HELP= '說明'
L.State_HARM = '傷害'
L.Targeting = '目標瞄準'
L.ShowStates = '顯示狀態'
L.Set = '設定'
L.Save = '儲存'
L.Copy = '複製'
L.Delete = '刪除'
L.Bar = '列 %d'
L.RightClickUnit = '在目標上按一下右鍵'
L.RCUPlayer = '本身'
L.RCUFocus = '焦點'
L.RCUToT = '目標的目標'
L.EnterName = '輸入名稱'
L.PossessBar = '控制列'
L.Profiles = '設定檔'
L.ProfilesPanelDesc = '可讓您管理已儲存的 RazerNaga 配置'
L.ShowMacroText = '顯示巨集文字'
L.ShowBindingText = '顯示綁定文字'
L.ShowEmptyButtons = '顯示空按鈕'
L.LockActionButtons = '鎖定動作按鈕的位置'
L.EnterBindingMode = '綁定按鍵...'
L.EnterConfigMode = '設定列...'
L.ActionBarSettings = '動作列 %d 設定'
L.BarSettings = '%s 列設定'
L.ShowTooltips = '顯示工具提示'
L.OneBag = '一袋'
L.ShowKeyring = '顯示鎖匙圈'
L.StickyBars = '設定巨集'
L.ShowMinimapButton = '顯示迷你地圖按鈕'
L.DisableMenuButtons = '鎖定鍵'
L.EnableAutoBindings = '永遠使用 Razer Naga 按鈕'
L.Bindings = '綁定'
L.BindingSetModifier = '輔助按鍵'

L.Advanced = '進階'
L.LeftToRight = '配置按鈕 (左到右)'
L.TopToBottom = '配置按鈕 (上到下)'
L.LinkedOpacity = '透明度顯示停靠條'
L.ClickThrough = '點擊此處'

--totems
L.ShowTotems = '顯示圖騰'
L.ShowTotemRecall = '顯示重播'

--modifier highlighting
L.HighlightModifiers = '反白顯示修改列'

L.ShowTooltipsCombat = '戰鬥中顯示工具列'