if not(GetLocale() == "koKR") then
    return;
end

local L = WeakAuras.L

-- Options translation
L["1 Match"] = "1개 일치" -- Needs review
-- L["Actions"] = ""
-- L["Activate when the given aura(s) |cFFFF0000can't|r be found"] = ""
L["Add a new display"] = "새 디스플레이 추가" -- Needs review
L["Add Dynamic Text"] = "유동적 텍스트 추가" -- Needs review
L["Addon"] = "애드온" -- Needs review
L["Addons"] = "애드온" -- Needs review
-- L["Add to group %s"] = ""
L["Add to new Dynamic Group"] = "새 유동적 그룹에 추가" -- Needs review
L["Add to new Group"] = "새 그룹 추가" -- Needs review
L["Add Trigger"] = "조건 추가" -- Needs review
-- L["A group that dynamically controls the positioning of its children"] = ""
L["Align"] = "조정" -- Needs review
-- L["Allow Full Rotation"] = ""
L["Alpha"] = "투명도" -- Needs review
L["Anchor"] = "기준점" -- Needs review
L["Anchor Point"] = "기준점" -- Needs review
L["Angle"] = "각도" -- Needs review
L["Animate"] = "애니메이션" -- Needs review
L["Animated Expand and Collapse"] = "확장 / 접기 애니메이션" -- Needs review
-- L["Animation relative duration description"] = ""
L["Animations"] = "애니메이션" -- Needs review
L["Animation Sequence"] = "애니메이션 순서" -- Needs review
-- L["Aquatic"] = ""
L["Aura (Paladin)"] = "오라 (성기사" -- Needs review
L["Aura(s)"] = "오라" -- Needs review
L["Auto"] = "자동" -- Needs review
L["Auto-cloning enabled"] = "자동 복제 활성화" -- Needs review
L["Automatic Icon"] = "자동 아이콘" -- Needs review
L["Backdrop Color"] = "배경 색상" -- Needs review
L["Backdrop Style"] = "배경 스타일" -- Needs review
L["Background"] = "배경" -- Needs review
L["Background Color"] = "배경 색상" -- Needs review
-- L["Background Inset"] = ""
-- L["Background Offset"] = ""
L["Background Texture"] = "배경 텍스쳐" -- Needs review
L["Bar Alpha"] = "바 투명도" -- Needs review
L["Bar Color"] = "바 색상" -- Needs review
L["Bar Color Settings"] = "바 색상 설정" -- Needs review
L["Bar in Front"] = "바에서 사용 할 폰트" -- Needs review
L["Bar Texture"] = "바 텍스쳐" -- Needs review
-- L["Battle"] = ""
L["Bear"] = "곰" -- Needs review
-- L["Berserker"] = ""
L["Blend Mode"] = "혼합 모드" -- Needs review
-- L["Blood"] = ""
L["Border"] = "테두리" -- Needs review
L["Border Color"] = "테두리 색상" -- Needs review
-- L["Border Inset"] = ""
-- L["Border Offset"] = ""
L["Border Settings"] = "테두리 설정" -- Needs review
L["Border Size"] = "테두리 크기" -- Needs review
L["Border Style"] = "테두리 스타일" -- Needs review
L["Bottom Text"] = "아래쪽 텍스트" -- Needs review
-- L["Button Glow"] = ""
-- L["Can be a name or a UID (e.g., party1). Only works on friendly players in your group."] = ""
L["Cancel"] = "취소" -- Needs review
-- L["Cat"] = ""
L["Change the name of this display"] = "이 디스플레이의 이름 변경" -- Needs review
L["Channel Number"] = "채널 번호" -- Needs review
L["Check On..."] = "체크..." -- Needs review
L["Choose"] = "선택" -- Needs review
L["Choose Trigger"] = "조건 선택" -- Needs review
-- L["Choose whether the displayed icon is automatic or defined manually"] = ""
-- L["Clone option enabled dialog"] = ""
L["Close"] = "닫기" -- Needs review
L["Collapse"] = "접기" -- Needs review
L["Collapse all loaded displays"] = "로딩된 모든 디스플레이 접기" -- Needs review
L["Collapse all non-loaded displays"] = "로딩되지 않은 모든 디스플레이 접기" -- Needs review
L["Color"] = "색상" -- Needs review
L["Compress"] = "누르기" -- Needs review
-- L["Concentration"] = ""
-- L["Constant Factor"] = ""
L["Control-click to select multiple displays"] = "Control-click - 여러 디스플레이 선택" -- Needs review
-- L["Controls the positioning and configuration of multiple displays at the same time"] = ""
L["Convert to..."] = "변환중..." -- Needs review
L["Cooldown"] = "쿨다운" -- Needs review
L["Copy"] = "복사" -- Needs review
L["Copy settings from..."] = "설정 복사..." -- Needs review
L["Copy settings from another display"] = "다른 디스플레이에서 설정 복사" -- Needs review
L["Copy settings from %s"] = "%s에서 설정 복사" -- Needs review
-- L["Count"] = ""
L["Creating buttons: "] = "버튼 생성:" -- Needs review
L["Creating options: "] = "옵션 생성:" -- Needs review
L["Crop X"] = "X 자르기" -- Needs review
L["Crop Y"] = "Y " -- Needs review
-- L["Crusader"] = ""
L["Custom Code"] = "개인추가 코드" -- Needs review
L["Custom Trigger"] = "개인추가 조건" -- Needs review
-- L["Custom trigger event tooltip"] = ""
-- L["Custom trigger status tooltip"] = ""
-- L["Custom Untrigger"] = ""
-- L["Custom untrigger event tooltip"] = ""
L["Death"] = "죽음" -- Needs review
-- L["Death Rune"] = ""
L["Debuff Type"] = "디버프 유형" -- Needs review
L["Defensive"] = "방어" -- Needs review
L["Delete"] = "삭제" -- Needs review
L["Delete all"] = "모두 삭제" -- Needs review
-- L["Delete children and group"] = ""
L["Deletes this display - |cFF8080FFShift|r must be held down while clicking"] = "이 디스플레이 삭제 - |cFF8080FFShift|r키를 누르고 클릭해야 합니다" -- Needs review
L["Delete Trigger"] = "조건 삭제" -- Needs review
L["Desaturate"] = "흑백" -- Needs review
-- L["Devotion"] = ""
L["Disabled"] = "비활성화됨" -- Needs review
-- L["Discrete Rotation"] = ""
L["Display"] = "디스플레이" -- Needs review
L["Display Icon"] = "디스플레이 아이콘" -- Needs review
L["Display Text"] = "디스플레이 텍스트" -- Needs review
-- L["Distribute Horizontally"] = ""
-- L["Distribute Vertically"] = ""
L["Do not copy any settings"] = "설정을 복사하지 않음" -- Needs review
-- L["Do not group this display"] = ""
L["Duplicate"] = "복제" -- Needs review
L["Duration Info"] = "지속시간 정보" -- Needs review
L["Duration (s)"] = "지속시간 (s)" -- Needs review
L["Dynamic Group"] = "유동적 그룹" -- Needs review
-- L["Dynamic text tooltip"] = ""
L["Enabled"] = "활성화됨" -- Needs review
L["Enter an aura name, partial aura name, or spell id"] = "오라 이름 / 오라의 부분 이름 / 주문ID를 입력하세요," -- Needs review
L["Event Type"] = "이벤트 유형" -- Needs review
L["Expand"] = "확장" -- Needs review
L["Expand all loaded displays"] = "로딩된 모든 디스플레이 확장" -- Needs review
L["Expand all non-loaded displays"] = "로딩되지 않은 모드 디스플레이 확장" -- Needs review
L["Expand Text Editor"] = "텍스트 편집창 확장" -- Needs review
L["Expansion is disabled because this group has no children"] = "이 그룹은 자식이 없기 떄문에 확장이 비활성화되었습니다" -- Needs review
L["Export"] = "내보내기" -- Needs review
L["Export to Lua table..."] = "Lua table로 내보내기" -- Needs review
L["Export to string..."] = "문자열로 내보내기" -- Needs review
-- L["Fade"] = ""
L["Finish"] = "완료" -- Needs review
L["Fire Resistance"] = "화염 저항" -- Needs review
-- L["Flight(Non-Feral)"] = ""
L["Font"] = "폰트" -- Needs review
L["Font Flags"] = "폰트 효과" -- Needs review
L["Font Size"] = "폰트 크기" -- Needs review
L["Font Type"] = "폰트 종류" -- Needs review
L["Foreground Color"] = "앞면 색상" -- Needs review
L["Foreground Texture"] = "앞면 텍스쳐" -- Needs review
L["Form (Druid)"] = "폼 (드루이드)" -- Needs review
L["Form (Priest)"] = "형상 (사제)" -- Needs review
L["Form (Shaman)"] = "폼 (주술사)" -- Needs review
L["Form (Warlock)"] = "폼 (흑마법사)" -- Needs review
L["Frame"] = "프레임" -- Needs review
L["Frame Strata"] = "프레임 표시순위" -- Needs review
L["Frost"] = "냉기" -- Needs review
L["Frost Resistance"] = "냉기 저항" -- Needs review
L["Full Scan"] = "모두 스캔" -- Needs review
-- L["Ghost Wolf"] = ""
-- L["Glow Action"] = ""
-- L["Group aura count description"] = ""
L["Group Member Count"] = "그룹 멤버 수" -- Needs review
-- L["Group (verb)"] = ""
L["Height"] = "높이" -- Needs review
-- L["Hide this group's children"] = ""
L["Hide When Not In Group"] = "파티중이 아닐 때 숨기기" -- Needs review
-- L["Horizontal Align"] = ""
L["Icon Info"] = "아이콘 정보" -- Needs review
L["Ignored"] = "무시됨" -- Needs review
L["Ignore GCD"] = "글로벌CD 무시" -- Needs review
L["%i Matches"] = "%i 일치" -- Needs review
L["Import"] = "가져오기" -- Needs review
L["Import a display from an encoded string"] = "암호화된 문자열에서 디스플레이 가져오기" -- Needs review
L["Justify"] = "정렬" -- Needs review
L["Left Text"] = "왼쪽 텍스트" -- Needs review
L["Load"] = "불러오기" -- Needs review
L["Loaded"] = "로딩됨" -- Needs review
-- L["Main"] = ""
L["Main Trigger"] = "메인 조건" -- Needs review
L["Mana (%)"] = "마나 (%)" -- Needs review
L["Manage displays defined by Addons"] = "애드온에서 디스플레이 정의를 관리합니다" -- Needs review
L["Message Prefix"] = "메세지 말머리" -- Needs review
L["Message Suffix"] = "메세지 말꼬리" -- Needs review
-- L["Metamorphosis"] = ""
L["Mirror"] = "거울효과" -- Needs review
L["Model"] = "모델" -- Needs review
-- L["Moonkin/Tree/Flight(Feral)"] = ""
L["Move Down"] = "아래로 이동" -- Needs review
-- L["Move this display down in its group's order"] = ""
-- L["Move this display up in its group's order"] = ""
L["Move Up"] = "위로 이동" -- Needs review
L["Multiple Displays"] = "다중 디스플레이" -- Needs review
L["Multiple Triggers"] = "다중 조건" -- Needs review
-- L["Multiselect ignored tooltip"] = ""
-- L["Multiselect multiple tooltip"] = ""
-- L["Multiselect single tooltip"] = ""
-- L["Must be spelled correctly!"] = ""
L["Name Info"] = "이름 정보" -- Needs review
-- L["Negator"] = ""
L["New"] = "새로운" -- Needs review
L["Next"] = "다음" -- Needs review
-- L["No"] = ""
L["No Children"] = "자식 없음" -- Needs review
-- L["Not all children have the same value for this option"] = ""
L["Not Loaded"] = "로딩되지 않음" -- Needs review
L["No tooltip text"] = "툴팁 텍스트 없음" -- Needs review
L["% of Progress"] = "% 진행" -- Needs review
L["Okay"] = "확인" -- Needs review
L["On Hide"] = "숨겨짐" -- Needs review
-- L["Only match auras cast by people other than the player"] = ""
L["Only match auras cast by the player"] = "플레이어가 시전한 오라와 일치할때만" -- Needs review
L["On Show"] = "보여짐" -- Needs review
L["Operator"] = "연산자" -- Needs review
L["or"] = "혹은" -- Needs review
L["Orientation"] = "방향" -- Needs review
-- L["Other"] = ""
L["Outline"] = "외곽선" -- Needs review
-- L["Own Only"] = ""
L["Player Character"] = "플레이어 캐릭터" -- Needs review
L["Play Sound"] = "소리 재생" -- Needs review
-- L["Presence (DK)"] = ""
-- L["Presence (Rogue)"] = ""
-- L["Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = ""
-- L["Primary"] = ""
L["Progress Bar"] = "진행 바" -- Needs review
L["Progress Texture"] = "진행 텍스쳐" -- Needs review
-- L["Put this display in a group"] = ""
L["Ready For Use"] = "사용 가능" -- Needs review
L["Re-center X"] = "내부 X 좌표" -- Needs review
L["Re-center Y"] = "내부 Y 좌표" -- Needs review
-- L["Remaining Time Precision"] = ""
L["Remove this display from its group"] = "그룹에서 이 디스플레이 삭제" -- Needs review
L["Rename"] = "이름 변경" -- Needs review
-- L["Requesting display information"] = ""
L["Required For Activation"] = "활성화 필요" -- Needs review
-- L["Retribution"] = ""
L["Right-click for more options"] = "RightClick - 추가 옵션" -- Needs review
L["Right Text"] = "오른쪽 텍스트" -- Needs review
L["Rotate"] = "회전" -- Needs review
-- L["Rotate In"] = ""
-- L["Rotate Out"] = ""
L["Rotate Text"] = "텍스트 회전" -- Needs review
L["Rotation"] = "회전" -- Needs review
-- L["Same"] = ""
L["Search"] = "검색" -- Needs review
-- L["Secondary"] = ""
L["Send To"] = "보내기..." -- Needs review
L["Set tooltip description"] = "툴팁 설명 설정" -- Needs review
-- L["Shadow Dance"] = ""
-- L["Shadowform"] = ""
L["Shadow Resistance"] = "암흑 저항" -- Needs review
L["Shift-click to create chat link"] = "Shift-click - |cFF8800FF[채팅 링크] 생성" -- Needs review
-- L["Show all matches (Auto-clone)"] = ""
-- L["Show players that are |cFFFF0000not affected"] = ""
L["Shows a 3D model from the game files"] = "게임 데이터의 3D 모델 보이기" -- Needs review
L["Shows a custom texture"] = "개인추가 텍스쳐 보이기" -- Needs review
L["Shows a progress bar with name, timer, and icon"] = "이름 / 타이머 / 아이콘의 진행 바 보이기" -- Needs review
-- L["Shows a spell icon with an optional a cooldown overlay"] = ""
L["Shows a texture that changes based on duration"] = "지속시간을 텍스쳐로 나타냅니다" -- Needs review
-- L["Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = ""
-- L["Shows the remaining or expended time for an aura or timed event"] = ""
L["Show this group's children"] = "이 그룹의 자식 보이기" -- Needs review
L["Size"] = "크기" -- Needs review
-- L["Slide"] = ""
-- L["Slide In"] = ""
-- L["Slide Out"] = ""
L["Sort"] = "정렬" -- Needs review
L["Sound"] = "사운드" -- Needs review
L["Sound Channel"] = "사운드 채널" -- Needs review
L["Sound File Path"] = "사운드 파일 경로" -- Needs review
L["Space"] = "공간" -- Needs review
L["Space Horizontally"] = "수평 공간" -- Needs review
L["Space Vertically"] = "수직 공간" -- Needs review
L["Spell ID"] = "주문 ID" -- Needs review
-- L["Spell ID dialog"] = ""
L["Stack Count"] = "묶음 카운트" -- Needs review
L["Stack Count Position"] = "중첩 횟수 위치" -- Needs review
L["Stack Info"] = "중첩 정보" -- Needs review
L["Stacks Settings"] = "묶음 설정" -- Needs review
-- L["Stagger"] = ""
L["Stance (Warrior)"] = "태세 (전사)" -- Needs review
L["Start"] = "시작" -- Needs review
L["Stealable"] = "훔치기 가능" -- Needs review
-- L["Stealthed"] = ""
-- L["Sticky Duration"] = ""
L["Temporary Group"] = "임시 그룹" -- Needs review
L["Text"] = "텍스트" -- Needs review
L["Text Color"] = "텍스트 색상" -- Needs review
L["Text Position"] = "텍스트 위치" -- Needs review
L["Text Settings"] = "텍스트 설정" -- Needs review
L["Texture"] = "텍스쳐" -- Needs review
-- L["The children of this group have different display types, so their display options cannot be set as a group."] = ""
-- L["The duration of the animation in seconds."] = ""
L["The type of trigger"] = "조건의 유형" -- Needs review
-- L["This condition will not be tested"] = ""
L["This display is currently loaded"] = "이 디스플레이 현재 로딩됨" -- Needs review
L["This display is not currently loaded"] = "이 디스플레이 현재 로딩되지 않음" -- Needs review
L["This display will only show when |cFF00FF00%s"] = "|cFF00FF00%s 일때만 이 디스플레이 보임" -- Needs review
L["This display will only show when |cFFFF0000 Not %s"] = "|cFFFF0000 Not %s 이지 않을때만 이 디스플레이 보임" -- Needs review
-- L["This region of type \"%s\" has no configuration options."] = ""
-- L["Time in"] = ""
L["Timer"] = "타이머" -- Needs review
L["Timer Settings"] = "타이머 설정" -- Needs review
L["Toggle the visibility of all loaded displays"] = "로딩된 모든 디스플레이 보이기 토글" -- Needs review
L["Toggle the visibility of all non-loaded displays"] = "로딩되지 않은 모든 디스플레이 보이기 토글" -- Needs review
L["Toggle the visibility of this display"] = "이 디스플레이 보이기 토글" -- Needs review
L["to group's"] = "그룹 기준" -- Needs review
L["Tooltip"] = "툴팁" -- Needs review
L["Tooltip on Mouseover"] = "마우스오버 툴팁" -- Needs review
L["Top Text"] = "윗부분 텍스트" -- Needs review
L["to screen's"] = "화면 기준" -- Needs review
-- L["Total Time Precision"] = ""
-- L["Tracking"] = ""
-- L["Travel"] = ""
L["Trigger"] = "조건" -- Needs review
L["Trigger %d"] = "조건 %d" -- Needs review
L["Triggers"] = "조건" -- Needs review
L["Type"] = "유형" -- Needs review
-- L["Ungroup"] = ""
L["Unholy"] = "부정" -- Needs review
-- L["Unit Exists"] = ""
-- L["Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = ""
L["Unstealthed"] = "은신풀림" -- Needs review
-- L["Update Custom Text On..."] = ""
L["Use Full Scan (High CPU)"] = "전체 스캔 사용 (높은 CPU 사용률)" -- Needs review
-- L["Use tooltip \"size\" instead of stacks"] = ""
L["Vertical Align"] = "수직 조정" -- Needs review
-- L["View"] = ""
L["Width"] = "가로" -- Needs review
L["X Offset"] = "X 좌표" -- Needs review
L["X Scale"] = "가로 크기" -- Needs review
L["Yes"] = "예" -- Needs review
L["Y Offset"] = "Y 좌표" -- Needs review
L["Y Scale"] = "세로 크기" -- Needs review
L["Z Offset"] = "Z 좌표" -- Needs review
L["Zoom"] = "줌" -- Needs review
L["Zoom In"] = "줌 인" -- Needs review
L["Zoom Out"] = "줌 아웃" -- Needs review



