if not(GetLocale() == "ptBR") then
    return;
end

local L = WeakAuras.L

-- Options translation
L["1 Match"] = "1 resultado" -- Needs review
L["Actions"] = "Ações" -- Needs review
L["Activate when the given aura(s) |cFFFF0000can't|r be found"] = "Ativar quando a aura(s) recebida |cFFFF0000não|r for(em) encontra(s)" -- Needs review
L["Add a new display"] = "Adicionar novo display" -- Needs review
L["Add Dynamic Text"] = "Adicionar texto dinâmico" -- Needs review
L["Addon"] = "Addon" -- Needs review
L["Addons"] = "Addons" -- Needs review
L["Add to group %s"] = "Adicionar a um grupo %s" -- Needs review
L["Add to new Dynamic Group"] = "Adicionar a um novo Grupo Dinâmico" -- Needs review
L["Add to new Group"] = "Adicionar a um novo Grupo" -- Needs review
L["Add Trigger"] = "Adicionar Gatilho" -- Needs review
L["A group that dynamically controls the positioning of its children"] = "Um grupo que controla dinamicamente o posicionamentos dos seus elementos" -- Needs review
L["Align"] = "Alinhar" -- Needs review
L["Allow Full Rotation"] = "Habilitar rotação completa" -- Needs review
L["Alpha"] = "Transparência" -- Needs review
L["Anchor"] = "Âncora" -- Needs review
L["Anchor Point"] = "Ponto da âncora" -- Needs review
L["Angle"] = "Ângulo" -- Needs review
L["Animate"] = "Animar" -- Needs review
L["Animated Expand and Collapse"] = "Animação expande e esvai" -- Needs review
-- L["Animation relative duration description"] = ""
L["Animations"] = "Animações" -- Needs review
L["Animation Sequence"] = "Sequência da animação" -- Needs review
L["Aquatic"] = "Aquático" -- Needs review
L["Aura (Paladin)"] = "Aura (Paladino)" -- Needs review
L["Aura(s)"] = "Aura(s)" -- Needs review
L["Auto"] = "Auto" -- Needs review
L["Auto-cloning enabled"] = "Autoclonagem habilitada" -- Needs review
L["Automatic Icon"] = "Ícone automático" -- Needs review
-- L["Backdrop Color"] = ""
-- L["Backdrop Style"] = ""
L["Background"] = "Fundo" -- Needs review
L["Background Color"] = "Cor de fundo" -- Needs review
L["Background Inset"] = "Inserção do fundo" -- Needs review
L["Background Offset"] = "Posicionamento do fundo" -- Needs review
L["Background Texture"] = "Textura do fundo" -- Needs review
L["Bar Alpha"] = "Transparência da barra" -- Needs review
L["Bar Color"] = "Cor da barra" -- Needs review
-- L["Bar Color Settings"] = ""
-- L["Bar in Front"] = ""
L["Bar Texture"] = "Textura da barra" -- Needs review
L["Battle"] = "Luta" -- Needs review
L["Bear"] = "Urso" -- Needs review
-- L["Berserker"] = ""
-- L["Blend Mode"] = ""
L["Blood"] = "Sangue" -- Needs review
L["Border"] = "Borda" -- Needs review
-- L["Border Color"] = ""
-- L["Border Inset"] = ""
L["Border Offset"] = "Posicionamento da borda" -- Needs review
-- L["Border Settings"] = ""
-- L["Border Size"] = ""
-- L["Border Style"] = ""
L["Bottom Text"] = "Texto na base" -- Needs review
L["Button Glow"] = "Iluminar botão" -- Needs review
-- L["Can be a name or a UID (e.g., party1). Only works on friendly players in your group."] = ""
L["Cancel"] = "Cancelar" -- Needs review
L["Cat"] = "Felino" -- Needs review
L["Change the name of this display"] = "Mudar o nome deste display" -- Needs review
L["Channel Number"] = "Número do canal" -- Needs review
L["Check On..."] = "Verificar..." -- Needs review
L["Choose"] = "Escolher" -- Needs review
L["Choose Trigger"] = "Escolher o gatilho" -- Needs review
L["Choose whether the displayed icon is automatic or defined manually"] = "Escolher se o ícone mostrado é automático ou definido manualmente" -- Needs review
-- L["Clone option enabled dialog"] = ""
L["Close"] = "Fechar" -- Needs review
-- L["Collapse"] = ""
-- L["Collapse all loaded displays"] = ""
-- L["Collapse all non-loaded displays"] = ""
L["Color"] = "Cor" -- Needs review
L["Compress"] = "Comprimir" -- Needs review
L["Concentration"] = "Concentração" -- Needs review
L["Constant Factor"] = "Fator constante" -- Needs review
L["Control-click to select multiple displays"] = "Ctrl+clique para selecionar displays múltiplos" -- Needs review
L["Controls the positioning and configuration of multiple displays at the same time"] = "Controla o posicionamento e a configuração de múltiplos displays ao mesmo tempo" -- Needs review
L["Convert to..."] = "Converter para..." -- Needs review
L["Cooldown"] = "Tempo de recarga" -- Needs review
L["Copy"] = "Copiar" -- Needs review
L["Copy settings from..."] = "Copiar as configurações de..." -- Needs review
L["Copy settings from another display"] = "Copiar as configurações de outro mostrador" -- Needs review
L["Copy settings from %s"] = "Copiar configurações de %s" -- Needs review
L["Count"] = "Contar" -- Needs review
L["Creating buttons: "] = "Criando botões:" -- Needs review
L["Creating options: "] = "Criando opções:" -- Needs review
L["Crop X"] = "Cortar X" -- Needs review
L["Crop Y"] = "Cortar Y" -- Needs review
L["Crusader"] = "Cruzado" -- Needs review
L["Custom Code"] = "Código personalizado" -- Needs review
L["Custom Trigger"] = "Gatilho personalizado" -- Needs review
-- L["Custom trigger event tooltip"] = ""
-- L["Custom trigger status tooltip"] = ""
-- L["Custom Untrigger"] = ""
-- L["Custom untrigger event tooltip"] = ""
L["Death"] = "Morte" -- Needs review
L["Death Rune"] = "Runa da morte" -- Needs review
L["Debuff Type"] = "Tipo de penalidade" -- Needs review
L["Defensive"] = "Defensivo" -- Needs review
L["Delete"] = "Apagar" -- Needs review
L["Delete all"] = "Apagar tudo" -- Needs review
L["Delete children and group"] = "Apagar as crianças e o grupo" -- Needs review
L["Deletes this display - |cFF8080FFShift|r must be held down while clicking"] = "Apagar este painel" -- Needs review
L["Delete Trigger"] = "Apagar gatilho" -- Needs review
L["Desaturate"] = "Descolorir" -- Needs review
L["Devotion"] = "Devoção" -- Needs review
L["Disabled"] = "Desabilitar" -- Needs review
L["Discrete Rotation"] = "Rotação discreta" -- Needs review
L["Display"] = "Mostruário" -- Needs review
L["Display Icon"] = "Ícone do mostruário" -- Needs review
L["Display Text"] = "Texto do mostruário" -- Needs review
L["Distribute Horizontally"] = "Distribuir horizontalmente" -- Needs review
L["Distribute Vertically"] = "Distribuir verticalmente" -- Needs review
L["Do not copy any settings"] = "Não copie qualquer configuração" -- Needs review
L["Do not group this display"] = "Não agrupe este mostruário" -- Needs review
L["Duplicate"] = "Duplicar" -- Needs review
L["Duration Info"] = "Informação da duração" -- Needs review
L["Duration (s)"] = "Duração" -- Needs review
L["Dynamic Group"] = "Grupo dinâmico" -- Needs review
-- L["Dynamic text tooltip"] = ""
L["Enabled"] = "Habilitado" -- Needs review
L["Enter an aura name, partial aura name, or spell id"] = "Entre um nome de aura, uma parte do nome da aura, ou id do feitiço" -- Needs review
L["Event Type"] = "Tipo de evento" -- Needs review
L["Expand"] = "Expandir" -- Needs review
L["Expand all loaded displays"] = "Expandir todos os mostruários carregados" -- Needs review
L["Expand all non-loaded displays"] = "Expandir todos os mostruários não carregados" -- Needs review
L["Expand Text Editor"] = "Expandir o editor de texto" -- Needs review
L["Expansion is disabled because this group has no children"] = "A expansão está desabilitada porque este grupo não tem nenhuma criança" -- Needs review
L["Export"] = "Exportar" -- Needs review
L["Export to Lua table..."] = "Exportar para tabela Lua" -- Needs review
L["Export to string..."] = "Exportar para uma string" -- Needs review
L["Fade"] = "Sumir" -- Needs review
L["Finish"] = "Finalizar" -- Needs review
L["Fire Resistance"] = "Resistência ao fogo" -- Needs review
L["Flight(Non-Feral)"] = "Luta(não-fera)" -- Needs review
L["Font"] = "Fonte" -- Needs review
-- L["Font Flags"] = ""
-- L["Font Size"] = ""
-- L["Font Type"] = ""
L["Foreground Color"] = "Cor do primeiro plano" -- Needs review
L["Foreground Texture"] = "Textura do primeiro plano" -- Needs review
L["Form (Druid)"] = "Forma" -- Needs review
L["Form (Priest)"] = "Forma" -- Needs review
L["Form (Shaman)"] = "Forma" -- Needs review
L["Form (Warlock)"] = "Forma" -- Needs review
L["Frame"] = "Quadro" -- Needs review
L["Frame Strata"] = "Camada do quadro" -- Needs review
L["Frost"] = "Gélido" -- Needs review
L["Frost Resistance"] = "Resistência ao gélido" -- Needs review
L["Full Scan"] = "Escaneamento completo" -- Needs review
L["Ghost Wolf"] = "Lobo fantasma" -- Needs review
L["Glow Action"] = "Ação incandescente" -- Needs review
-- L["Group aura count description"] = ""
L["Group Member Count"] = "Contagem dos membros do grupo" -- Needs review
L["Group (verb)"] = "Agrupar" -- Needs review
L["Height"] = "Altura" -- Needs review
L["Hide this group's children"] = "Esconder as crianças deste grupo" -- Needs review
L["Hide When Not In Group"] = "Esconder quando em grupo" -- Needs review
L["Horizontal Align"] = "Alinhamento horizontal" -- Needs review
L["Icon Info"] = "Informação do ícone" -- Needs review
L["Ignored"] = "Ignorado" -- Needs review
L["Ignore GCD"] = "Ignorar GCD" -- Needs review
L["%i Matches"] = "%i resultados" -- Needs review
L["Import"] = "Importar" -- Needs review
L["Import a display from an encoded string"] = "Importar um display de um string codificado" -- Needs review
L["Justify"] = "Justificar" -- Needs review
L["Left Text"] = "Texto à esquerda" -- Needs review
-- L["Load"] = ""
L["Loaded"] = "Carrregar" -- Needs review
L["Main"] = "Principal" -- Needs review
L["Main Trigger"] = "Gatilho principal" -- Needs review
L["Mana (%)"] = "Mana (%)" -- Needs review
L["Manage displays defined by Addons"] = "Gerencia os displays definidos por addons" -- Needs review
L["Message Prefix"] = "Prefixo de mensagem" -- Needs review
L["Message Suffix"] = "Sufixo de mensagem" -- Needs review
L["Metamorphosis"] = "Metamorfose" -- Needs review
L["Mirror"] = "Espelho" -- Needs review
L["Model"] = "Modelo" -- Needs review
L["Moonkin/Tree/Flight(Feral)"] = "Moonkin/Árvore/Vôo(Feral)" -- Needs review
L["Move Down"] = "Mover para baixo" -- Needs review
L["Move this display down in its group's order"] = "Move este display para baixo no ordenamento do seu grupo" -- Needs review
L["Move this display up in its group's order"] = "Move este display para cima no ordenamento do seu grupo" -- Needs review
L["Move Up"] = "Mover para cima" -- Needs review
L["Multiple Displays"] = "Múltiplos displays" -- Needs review
L["Multiple Triggers"] = "Múltiplos gatilhos" -- Needs review
-- L["Multiselect ignored tooltip"] = ""
-- L["Multiselect multiple tooltip"] = ""
-- L["Multiselect single tooltip"] = ""
L["Must be spelled correctly!"] = "Deve ser soletrado corretamente!" -- Needs review
L["Name Info"] = "Informação do nome" -- Needs review
L["Negator"] = "Negador" -- Needs review
L["New"] = "Novo" -- Needs review
L["Next"] = "Próximo" -- Needs review
L["No"] = "Não" -- Needs review
-- L["No Children"] = ""
-- L["Not all children have the same value for this option"] = ""
L["Not Loaded"] = "Não carregado" -- Needs review
-- L["No tooltip text"] = ""
L["% of Progress"] = "% do progresso" -- Needs review
L["Okay"] = "Okay" -- Needs review
L["On Hide"] = "Quando sumir" -- Needs review
-- L["Only match auras cast by people other than the player"] = ""
-- L["Only match auras cast by the player"] = ""
L["On Show"] = "Quando mostrar" -- Needs review
L["Operator"] = "Operador" -- Needs review
-- L["or"] = ""
L["Orientation"] = "Orientação" -- Needs review
L["Other"] = "Outro" -- Needs review
L["Outline"] = "Contorno" -- Needs review
L["Own Only"] = "Apenas meu" -- Needs review
L["Player Character"] = "Personagem do jogador" -- Needs review
L["Play Sound"] = "Reproduzir som" -- Needs review
L["Presence (DK)"] = "Presença (CM)" -- Needs review
L["Presence (Rogue)"] = "Presença (Ladino)" -- Needs review
-- L["Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = ""
L["Primary"] = "Primário" -- Needs review
L["Progress Bar"] = "Barra de progresso" -- Needs review
L["Progress Texture"] = "Textura de progresso" -- Needs review
L["Put this display in a group"] = "Colocar este display em um grupo" -- Needs review
L["Ready For Use"] = "Pronto para uso" -- Needs review
L["Re-center X"] = "Recentralizar X" -- Needs review
L["Re-center Y"] = "Recentralizar Y" -- Needs review
L["Remaining Time Precision"] = "Precisão do tempo restante" -- Needs review
L["Remove this display from its group"] = "Remover este display de um grupo" -- Needs review
L["Rename"] = "Renomear" -- Needs review
L["Requesting display information"] = "Solicitando informações do display de %s..." -- Needs review
L["Required For Activation"] = "Requerido para ativar" -- Needs review
L["Retribution"] = "Retribuição" -- Needs review
L["Right-click for more options"] = "Clique-direito para mais opções" -- Needs review
L["Right Text"] = "Texto à direita" -- Needs review
L["Rotate"] = "Girar" -- Needs review
L["Rotate In"] = "Girar para dentro" -- Needs review
L["Rotate Out"] = "Girar para fora" -- Needs review
L["Rotate Text"] = "Girar o texto" -- Needs review
L["Rotation"] = "Rotação" -- Needs review
L["Same"] = "Mesmo" -- Needs review
L["Search"] = "Procurar" -- Needs review
L["Secondary"] = "Secundário" -- Needs review
L["Send To"] = "Enviar para" -- Needs review
-- L["Set tooltip description"] = ""
L["Shadow Dance"] = "Dança das sombras" -- Needs review
L["Shadowform"] = "Forma de sombra" -- Needs review
L["Shadow Resistance"] = "Resistência às sombras" -- Needs review
L["Shift-click to create chat link"] = "Shift-clique para criar um link na conversa" -- Needs review
L["Show all matches (Auto-clone)"] = "Mostrar todas as correspondências" -- Needs review
L["Show players that are |cFFFF0000not affected"] = "Mostrar todos os jogadores que |cFFFF0000não foram afetados" -- Needs review
L["Shows a 3D model from the game files"] = "Mostrar um modelo 3D dos arquivos do jogo" -- Needs review
L["Shows a custom texture"] = "Mostrar uma textura personalizada" -- Needs review
L["Shows a progress bar with name, timer, and icon"] = "Mostrar uma barra de progresso com nome, temporizador e ícone" -- Needs review
L["Shows a spell icon with an optional a cooldown overlay"] = "Mostrar um ícone de feitiço com o opcional do tempo de recarga sobreposto" -- Needs review
L["Shows a texture that changes based on duration"] = "Mostrar uma textura que muda com base na duração" -- Needs review
L["Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = "Mostra uma ou mais linhas de texto, que podem incluir informações dinâmicas tal como progresso ou quantidades" -- Needs review
L["Shows the remaining or expended time for an aura or timed event"] = "Mostra o tempo restante ou expedido de uma aura ou evento cronometrado" -- Needs review
-- L["Show this group's children"] = ""
L["Size"] = "Tamanho" -- Needs review
L["Slide"] = "Deslizar" -- Needs review
L["Slide In"] = "Deslizar para dentro" -- Needs review
L["Slide Out"] = "Deslizar para fora" -- Needs review
L["Sort"] = "Ordenar" -- Needs review
L["Sound"] = "Som" -- Needs review
L["Sound Channel"] = "Canal de som" -- Needs review
L["Sound File Path"] = "Caminho do arquivo de som" -- Needs review
L["Space"] = "Espaço" -- Needs review
L["Space Horizontally"] = "Espaço horizontal" -- Needs review
-- L["Space Vertically"] = ""
-- L["Spell ID"] = ""
-- L["Spell ID dialog"] = ""
-- L["Stack Count"] = ""
-- L["Stack Count Position"] = ""
-- L["Stack Info"] = ""
-- L["Stacks Settings"] = ""
-- L["Stagger"] = ""
-- L["Stance (Warrior)"] = ""
-- L["Start"] = ""
-- L["Stealable"] = ""
-- L["Stealthed"] = ""
-- L["Sticky Duration"] = ""
-- L["Temporary Group"] = ""
-- L["Text"] = ""
-- L["Text Color"] = ""
-- L["Text Position"] = ""
-- L["Text Settings"] = ""
-- L["Texture"] = ""
-- L["The children of this group have different display types, so their display options cannot be set as a group."] = ""
-- L["The duration of the animation in seconds."] = ""
-- L["The type of trigger"] = ""
-- L["This condition will not be tested"] = ""
-- L["This display is currently loaded"] = ""
-- L["This display is not currently loaded"] = ""
-- L["This display will only show when |cFF00FF00%s"] = ""
-- L["This display will only show when |cFFFF0000 Not %s"] = ""
-- L["This region of type \"%s\" has no configuration options."] = ""
-- L["Time in"] = ""
-- L["Timer"] = ""
-- L["Timer Settings"] = ""
-- L["Toggle the visibility of all loaded displays"] = ""
-- L["Toggle the visibility of all non-loaded displays"] = ""
-- L["Toggle the visibility of this display"] = ""
-- L["to group's"] = ""
-- L["Tooltip"] = ""
-- L["Tooltip on Mouseover"] = ""
-- L["Top Text"] = ""
-- L["to screen's"] = ""
-- L["Total Time Precision"] = ""
-- L["Tracking"] = ""
-- L["Travel"] = ""
-- L["Trigger"] = ""
-- L["Trigger %d"] = ""
-- L["Triggers"] = ""
-- L["Type"] = ""
-- L["Ungroup"] = ""
-- L["Unholy"] = ""
-- L["Unit Exists"] = ""
-- L["Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = ""
-- L["Unstealthed"] = ""
-- L["Update Custom Text On..."] = ""
-- L["Use Full Scan (High CPU)"] = ""
-- L["Use tooltip \"size\" instead of stacks"] = ""
-- L["Vertical Align"] = ""
-- L["View"] = ""
-- L["Width"] = ""
-- L["X Offset"] = ""
-- L["X Scale"] = ""
-- L["Yes"] = ""
-- L["Y Offset"] = ""
-- L["Y Scale"] = ""
-- L["Z Offset"] = ""
-- L["Zoom"] = ""
-- L["Zoom In"] = ""
-- L["Zoom Out"] = ""



